### ISSUE TITLE
扫描 TypeScript 时，Scanner 出错

### ISSUE THREAD

**Issue by chenhhhhhhhhh** [archguard/archguard#108]
<img width="1527" alt="image" src="https://user-images.githubusercontent.com/95460130/177747455-cc924627-054d-4f07-9653-564536d86556.png">

2022-07-07 17:42:12.496 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - todo -> need support type: ObjectLiteralExpressionContext ==== {value:true}
2022-07-07 17:42:12.496 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - enterExpressionStatement -> IdentifierExpressionContext: exports.
2022-07-07 17:42:12.723 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - Exception in thread "main" java.lang.NullPointerException
2022-07-07 17:42:12.724 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient -     at chapi.ast.typescriptast.TypeScriptFullIdentListener.enterFunctionDeclaration(TypeScriptFullIdentListener.kt:425)
2022-07-07 17:42:12.724 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient -     at chapi.ast.antlr.TypeScriptParser$FunctionDeclarationContext.enterRule(TypeScriptParser.java:10017)
2022-07-07 17:42:12.724 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient -     at org.antlr.v4.runtime.tree.ParseTreeWalker.enterRule(ParseTreeWalker.java:50)
2022-07-07 17:42:12.724 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient -     at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:33)
2022-07-07 17:42:12.724 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient -     at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36)
2022-07-07 17:42:12.724 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient -     at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36)
2022-07-07 17:42:12.724 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient -     at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36)
2022-07-07 17:42:12.724 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient -     at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36)
2022-07-07 17:42:12.724 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient -     at chapi.ast.typescriptast.TypeScriptAnalyser.analysis(TypeScriptAnalyser.kt:14)
2022-07-07 17:42:12.724 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient -     at org.archguard.scanner.analyser.TypeScriptAnalyser.analysisByFile(TypeScriptAnalyser.kt:42)
2022-07-07 17:42:12.724 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient -     at org.archguard.scanner.analyser.TypeScriptAnalyser.access$analysisByFile(TypeScriptAnalyser.kt:12)
2022-07-07 17:42:12.724 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient -     at org.archguard.scanner.analyser.TypeScriptAnalyser$analyse$1$2$1.invokeSuspend(TypeScriptAnalyser.kt:35)
2022-07-07 17:42:12.725 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient -     at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2022-07-07 17:42:12.725 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient -     at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2022-07-07 17:42:12.726 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient -     at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:279)
2022-07-07 17:42:12.726 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient -     at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
2022-07-07 17:42:12.726 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient -     at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
2022-07-07 17:42:12.726 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient -     at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
2022-07-07 17:42:12.727 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient -     at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
2022-07-07 17:42:12.729 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient -     at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
2022-07-07 17:42:12.729 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient -     at org.archguard.scanner.analyser.TypeScriptAnalyser.analyse(TypeScriptAnalyser.kt:19)
2022-07-07 17:42:12.729 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient -     at org.archguard.scanner.core.sourcecode.LanguageSourceCodeAnalyser$DefaultImpls.analyse(LanguageSourceCodeAnalyser.kt:10)
2022-07-07 17:42:12.729 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient -     at org.archguard.scanner.analyser.TypeScriptAnalyser.analyse(TypeScriptAnalyser.kt:12)
2022-07-07 17:42:12.729 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient -     at org.archguard.scanner.ctl.loader.SourceCodeWorker$run$1.invokeSuspend(AnalyserDispatcher.kt:71)
2022-07-07 17:42:12.729 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient -     at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2022-07-07 17:42:12.729 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient -     at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2022-07-07 17:42:12.729 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient -     at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:279)
2022-07-07 17:42:12.729 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient -     at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
2022-07-07 17:42:12.729 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient -     at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
2022-07-07 17:42:12.730 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient -     at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
2022-07-07 17:42:12.730 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient -     at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
2022-07-07 17:42:12.730 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient -     at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
2022-07-07 17:42:12.730 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient -     at org.archguard.scanner.ctl.loader.SourceCodeWorker.run(AnalyserDispatcher.kt:69)
2022-07-07 17:42:12.730 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient -     at org.archguard.scanner.ctl.loader.AnalyserDispatcher.dispatch(AnalyserDispatcher.kt:34)
2022-07-07 17:42:12.730 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient -     at org.archguard.scanner.ctl.Runner.run(Runner.kt:92)
2022-07-07 17:42:12.730 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient -     at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:198)
2022-07-07 17:42:12.730 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient -     at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:18)
2022-07-07 17:42:12.730 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient -     at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:395)
2022-07-07 17:42:12.730 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient -     at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:392)
2022-07-07 17:42:12.730 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient -     at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:410)
2022-07-07 17:42:12.730 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient -     at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:435)
2022-07-07 17:42:12.730 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient -     at org.archguard.scanner.ctl.RunnerKt.main(Runner.kt:96)

**Comment by phodal** [comment]
看样子是应该是扫描 TypeScript 的时候出错了，错误是在 Chapi 里：

```
2022-07-07 17:42:12.496 [DefaultDispatcher-worker-2] INFO c.t.a.s.infra.ScannerCliClient - todo -> need support type: ObjectLiteralExpressionContext ==== {value:true}
2022-07-07 17:42:12.496 [DefaultDispatcher-worker-2] INFO c.t.a.s.infra.ScannerCliClient - enterExpressionStatement -> IdentifierExpressionContext: exports.
2022-07-07 17:42:12.723 [DefaultDispatcher-worker-2] INFO c.t.a.s.infra.ScannerCliClient - Exception in thread "main" java.lang.NullPointerException
2022-07-07 17:42:12.724 [DefaultDispatcher-worker-2] INFO c.t.a.s.infra.ScannerCliClient - at chapi.ast.typescriptast.TypeScriptFullIdentListener.enterFunctionDeclaration(TypeScriptFullIdentListener.kt:425)
2022-07-07 17:42:12.724 [DefaultDispatcher-worker-2] INFO c.t.a.s.infra.ScannerCliClient - at chapi.ast.antlr.TypeScriptParser$FunctionDeclarationContext.enterRule(TypeScriptParser.java:10017)
2022-07-07 17:42:12.724 [DefaultDispatcher-worker-2] INFO c.t.a.s.infra.ScannerCliClient - at 
```

修复需要一定的时间，主要是得找到出错的代码。你这边能往上翻一下日志，看看出错的文件的代码吗？

**Comment by chenhhhhhhhhh** [comment]
前面的部分屏幕打印

2022-07-07 17:42:10.753 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - todo -> need support type: FunctionExpressionContext ==== function(file){varpathName=path.join(folderPath,file);varstat=fs.statSync(pathName)if(stat.isDirectory()){if(file.indexOf('_')!==0){walk(pathName+'/',callback,depth+1);}else{callback(file,res,false);}}else{(file.indexOf('.')>0)&&(file.indexOf('_')!==0)&&res.push(folderPath+file);}}
2022-07-07 17:42:10.753 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - enterFunctionExpressionDeclaration -> ArgumentContext, function(file){varpathName=path.join(folderPath,file);varstat=fs.statSync(pathName)if(stat.isDirectory()){if(file.indexOf('_')!==0){walk(pathName+'/',callback,depth+1);}else{callback(file,res,false);}}else{(file.indexOf('.')>0)&&(file.indexOf('_')!==0)&&res.push(folderPath+file);}} 
2022-07-07 17:42:10.753 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - variableToFields -> path.join(folderPath,file) === ArgumentsExpressionContext
2022-07-07 17:42:10.754 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - variableToFields -> fs.statSync(pathName) === ArgumentsExpressionContext
2022-07-07 17:42:10.754 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - enterExpressionStatement : LogicalAndExpressionContext
2022-07-07 17:42:10.754 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - enterExpressionStatement : LogicalAndExpressionContext
2022-07-07 17:42:10.754 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - variableToFields -> function(regex,replacement){returngulp_replace(regex,replacement);} === FunctionExpressionContext
2022-07-07 17:42:10.754 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - enterVariableDeclaration : FunctionExpressionContext === replace=function(regex,replacement){returngulp_replace(regex,replacement);}
2022-07-07 17:42:10.755 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - variableToFields -> function(a,b){if(fs.existsSync(b)){returnfs.readFileSync(b);}} === FunctionExpressionContext
2022-07-07 17:42:10.755 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - enterVariableDeclaration : FunctionExpressionContext === importRes=function(a,b){if(fs.existsSync(b)){returnfs.readFileSync(b);}}
2022-07-07 17:42:10.755 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - variableToFields -> (assetUrl)=>{assetUrl=path.normalize(assetUrl);returnpath.sep==='\\'?assetUrl.replace(/\\/g,'\/'):assetUrl;} === ArrowFunctionExpressionContext
2022-07-07 17:42:10.755 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - parseStmt childType -> :VariableStatementContext
2022-07-07 17:42:10.756 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - todo -> need support type: TernaryExpressionContext ==== path.sep==='\\'?assetUrl.replace(/\\/g,'\/'):assetUrl
2022-07-07 17:42:10.756 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - variableToFields -> path.normalize(assetUrl) === ArgumentsExpressionContext
2022-07-07 17:42:10.756 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - variableToFields -> (baseDir,assetsPath,relative)=>path.resolve(baseDir,assetsPath||'',relative||'') === ArrowFunctionExpressionContext
2022-07-07 17:42:10.756 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - enterExpressionStatement : AssignmentExpressionContext
2022-07-07 17:42:10.930 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - IdentifierExpressionContext -> others variable decl: require ==== require('fs')
2022-07-07 17:42:10.931 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - IdentifierExpressionContext -> others variable decl: require ==== require('path')
2022-07-07 17:42:10.931 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - enterVariableDeclaration : LiteralExpressionContext === jestDir='tools/jest'
2022-07-07 17:42:10.932 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - variableToFields -> [{src:'tools/jest/@jest/core/update_global_config.js',dest:'node_modules/@jest/core/build/lib/update_global_config.js'},{src:'tools/jest/@jest/core/watch.js',dest:'node_modules/@jest/core/build/watch.js'},{src:'tools/jest/@jest/reporters/coverage_reporter.js',dest:'node_modules/@jest/reporters/build/coverage_reporter.js'},{src:'tools/jest/@jest/reporters/generateEmptyCoverage.js',dest:'node_modules/@jest/reporters/build/generateEmptyCoverage.js'},{src:'tools/jest/@jest/reporters/get_watermarks.js',dest:'node_modules/@jest/reporters/build/get_watermarks.js'},{src:'tools/jest/@jest/transform/shouldInstrument.js',dest:'node_modules/@jest/transform/build/shouldInstrument.js'},{src:'tools/jest/jest-config/index.js',dest:'node_modules/jest-config/build/index.js'},{src:'tools/jest/jest-runner/runTest.js',dest:'node_modules/jest-runner/build/runTest.js'},] === ArrayLiteralExpressionContext
2022-07-07 17:42:10.932 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - enterVariableDeclaration : ArrayLiteralExpressionContext === files=[{src:'tools/jest/@jest/core/update_global_config.js',dest:'node_modules/@jest/core/build/lib/update_global_config.js'},{src:'tools/jest/@jest/core/watch.js',dest:'node_modules/@jest/core/build/watch.js'},{src:'tools/jest/@jest/reporters/coverage_reporter.js',dest:'node_modules/@jest/reporters/build/coverage_reporter.js'},{src:'tools/jest/@jest/reporters/generateEmptyCoverage.js',dest:'node_modules/@jest/reporters/build/generateEmptyCoverage.js'},{src:'tools/jest/@jest/reporters/get_watermarks.js',dest:'node_modules/@jest/reporters/build/get_watermarks.js'},{src:'tools/jest/@jest/transform/shouldInstrument.js',dest:'node_modules/@jest/transform/build/shouldInstrument.js'},{src:'tools/jest/jest-config/index.js',dest:'node_modules/jest-config/build/index.js'},{src:'tools/jest/jest-runner/runTest.js',dest:'node_modules/jest-runner/build/runTest.js'},]
2022-07-07 17:42:10.933 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - variableToFields -> [resolve(__dirname,'../',jestDir)] === ArrayLiteralExpressionContext
2022-07-07 17:42:10.934 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - enterVariableDeclaration : ArrayLiteralExpressionContext === dirs=[resolve(__dirname,'../',jestDir)]
2022-07-07 17:42:10.934 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - todo -> need support type: ArrowFunctionExpressionContext ==== (dir)=>{if(!fs.existsSync(dir)){fs.mkdirSync(dir,{recursive:true});}}
2022-07-07 17:42:10.934 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - parseStmt childType -> :IfStatementContext
2022-07-07 17:42:10.934 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - todo -> need support type: ObjectLiteralExpressionContext ==== {recursive:true}
2022-07-07 17:42:10.934 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - todo -> need support type: ArrowFunctionExpressionContext ==== file=>{constsrc=resolve(__dirname,'../',file.src);constdest=resolve(__dirname,'../',file.dest);fs.copyFileSync(src,dest);}
2022-07-07 17:42:10.935 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - parseStmt childType -> :VariableStatementContext
2022-07-07 17:42:10.935 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - parseStmt childType -> :VariableStatementContext
2022-07-07 17:42:10.935 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - parseStmt childType -> :ExpressionStatementContext
2022-07-07 17:42:10.935 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - todo -> ParenthesizedExpressionContext: MemberDotExpressionContext, text: file.src
2022-07-07 17:42:10.935 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - IdentifierExpressionContext -> others variable decl: resolve ==== resolve(__dirname,'../',file.src)
2022-07-07 17:42:10.935 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - todo -> ParenthesizedExpressionContext: MemberDotExpressionContext, text: file.dest
2022-07-07 17:42:10.935 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - IdentifierExpressionContext -> others variable decl: resolve ==== resolve(__dirname,'../',file.dest)
2022-07-07 17:42:11.614 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - parseStmt childType -> :ExpressionStatementContext
2022-07-07 17:42:11.614 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - parseStmt childType -> :ExpressionStatementContext
2022-07-07 17:42:11.631 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - argText with ).[]
2022-07-07 17:42:11.631 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - enterExpressionStatement -> IdentifierExpressionContext: constset=newSet()
2022-07-07 17:42:11.631 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - todo -> need support type: ArrowFunctionExpressionContext ==== testCase=>{constauthor=testCase.author||testCase.defaultTestBaseInfo.author;set.add(author);}
2022-07-07 17:42:11.631 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - todo -> need support type: EqualityExpressionContext ==== testCase.status==="failed"
2022-07-07 17:42:11.631 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - parseStmt childType -> :VariableStatementContext
2022-07-07 17:42:11.631 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - parseStmt childType -> :ExpressionStatementContext
2022-07-07 17:42:11.632 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - variableToFields -> testCase.author||testCase.defaultTestBaseInfo.author === LogicalOrExpressionContext
2022-07-07 17:42:11.632 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - enterVariableDeclaration : LogicalOrExpressionContext === author=testCase.author||testCase.defaultTestBaseInfo.author
2022-07-07 17:42:11.632 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - MemberDotExpressionContext: -> MemberDotExpressionContext
2022-07-07 17:42:11.632 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - argText with ).[]
2022-07-07 17:42:11.632 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - todo -> need support type: LogicalOrExpressionContext ==== testResult.numFailingTests>0||testResult.testExecError
2022-07-07 17:42:11.633 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - parseStmt childType -> :VariableStatementContext
2022-07-07 17:42:11.633 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - parseStmt childType -> :VariableStatementContext
2022-07-07 17:42:11.633 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - todo -> need support type: ObjectLiteralExpressionContext ==== {filePath,author,numFailingTests:testResult.numFailingTests,testExecError:testResult.testExecError,}
2022-07-07 17:42:11.633 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - variableToFields -> testResult.testFilePath.replace(publicPath,'') === ArgumentsExpressionContext
2022-07-07 17:42:11.633 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - variableToFields -> testResult.testExecError?'paddywu':getAuthor(testResult) === TernaryExpressionContext
2022-07-07 17:42:11.633 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - enterVariableDeclaration : TernaryExpressionContext === author=testResult.testExecError?'paddywu':getAuthor(testResult)
2022-07-07 17:42:11.633 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - parseStmt childType -> :VariableStatementContext
2022-07-07 17:42:11.633 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - parseStmt childType -> :IfStatementContext
2022-07-07 17:42:11.633 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - parseStmt childType -> :IfStatementContext
2022-07-07 17:42:11.634 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - variableToFields -> JSON.parse(globalThis.resData) === ArgumentsExpressionContext
2022-07-07 17:42:11.634 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - IdentifierExpressionContext -> others variable decl: require ==== require('../../dwt-result.json')
2022-07-07 17:42:11.634 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - parseStmt childType -> :ExpressionStatementContext
2022-07-07 17:42:11.634 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - todo -> need support type: ArrowFunctionExpressionContext ==== (testCase)=>{constnumFailingTests=testCase.numFailingTests||'Exec Error';console.info(`| ${testCase.filePath} | ${testCase.author} | ${numFailingTests} |`);}
2022-07-07 17:42:11.635 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - parseStmt childType -> :IfStatementContext
2022-07-07 17:42:11.635 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - todo -> need support type: AdditiveExpressionContext ==== !!b.testExecError-!!a.testExecError
2022-07-07 17:42:11.636 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - parseStmt childType -> :VariableStatementContext
2022-07-07 17:42:11.636 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - parseStmt childType -> :ExpressionStatementContext
2022-07-07 17:42:11.636 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - variableToFields -> testCase.numFailingTests||'Exec Error' === LogicalOrExpressionContext
2022-07-07 17:42:11.636 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - enterVariableDeclaration : LogicalOrExpressionContext === numFailingTests=testCase.numFailingTests||'Exec Error'
2022-07-07 17:42:11.636 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - todo -> need support type: LiteralExpressionContext ==== `| ${testCase.filePath} | ${testCase.author} | ${numFailingTests} |`
2022-07-07 17:42:11.636 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - parseStmt childType -> :VariableStatementContext
2022-07-07 17:42:11.636 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - parseStmt childType -> :VariableStatementContext
2022-07-07 17:42:11.637 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - parseStmt childType -> :VariableStatementContext
2022-07-07 17:42:11.637 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - variableToFields -> getDwtResult() === ArgumentsExpressionContext
2022-07-07 17:42:11.637 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - IdentifierExpressionContext -> others variable decl: parseFailedCase ==== parseFailedCase(dwtResult,publicPath)
2022-07-07 17:42:11.887 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - line 7:8 no viable alternative at input '.default'
2022-07-07 17:42:11.887 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - line 7:16 mismatched input '=' expecting {'function', 'async'}
2022-07-07 17:42:12.197 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - line 176:0 rule expressionStatement failed predicate: {this.notOpenBraceAndNotFunction()}?
2022-07-07 17:42:12.483 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - line 202:9 no viable alternative at input '.default'
2022-07-07 17:42:12.483 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - line 202:17 mismatched input '=' expecting {'function', 'async'}
2022-07-07 17:42:12.493 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - line 207:0 mismatched input '}' expecting {<EOF>, RegularExpressionLiteral, '[', '(', '{', ';', '++', '--', '+', '-', '~', '!', '<', '_', '$', 'null', BooleanLiteral, DecimalLiteral, HexIntegerLiteral, OctalIntegerLiteral, OctalIntegerLiteral2, BinaryIntegerLiteral, 'break', 'do', 'instanceof', 'typeof', 'keyof', 'case', 'else', 'new', 'var', 'catch', 'finally', 'return', 'void', 'continue', 'for', 'switch', 'while', 'debugger', 'function', 'this', 'with', 'default', 'if', 'throw', 'delete', 'in', 'try', 'from', 'readonly', 'async', 'await', 'class', 'enum', 'extends', 'super', 'const', 'export', 'import', 'implements', 'let', 'private', 'public', 'interface', 'package', 'protected', 'static', 'yield', 'any', 'number', 'boolean', 'string', 'type', 'get', 'set', 'namespace', 'require', 'module', 'declare', 'undefined', 'abstract', 'is', '@', Identifier, StringLiteral, BackTick}
2022-07-07 17:42:12.495 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - enterExpressionStatement : LiteralExpressionContext
2022-07-07 17:42:12.496 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - todo -> need support type: LiteralExpressionContext ==== '__esModule'
2022-07-07 17:42:12.496 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - todo -> need support type: ObjectLiteralExpressionContext ==== {value:true}
2022-07-07 17:42:12.496 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - enterExpressionStatement -> IdentifierExpressionContext: exports.
2022-07-07 17:42:12.723 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - Exception in thread "main" java.lang.NullPointerException
2022-07-07 17:42:12.724 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient -     at chapi.ast.typescriptast.TypeScriptFullIdentListener.enterFunctionDeclaration(TypeScriptFullIdentListener.kt:425)
2022-07-07 17:42:12.724 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient -     at chapi.ast.antlr.TypeScriptParser$FunctionDeclarationContext.enterRule(TypeScriptParser.java:10017)
2022-07-07 17:42:12.724 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient -     at org.antlr.v4.runtime.tree.ParseTreeWalker.enterRule(ParseTreeWalker.java:50)
2022-07-07 17:42:12.724 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient -     at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:33)
2022-07-07 17:42:12.724 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient -     at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36)
2022-07-07 17:42:12.724 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient -     at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36)

**Comment by phodal** [comment]
感谢，我先简单修复了一下。晚上，我再看看有没有更好的方案。
