### ISSUE TITLE
版本2.0.0-beta.2扫描代码后没有生成结果

### ISSUE THREAD

**Issue by AllenShi** [archguard/archguard#119]
**Describe the bug**

**Env (please complete the following information):**
 - OS: Ubuntu虚拟机
 - Env: Docker compose
 - Browser：chrome
 - Version：clone Archguard最新版本2.0.0-beta.2

**To Reproduce**
1. 子系统分析页面选择新增系统
2.  填写系统github信息，如下截图所示
3.  在新增系统图标选择查询日志，内容如下截图所示。从archguard-backend的后台日志看，有如下内容：

```bash
2022-10-11 17:21:16.443 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient - [SCANNER] o.a.s.ctl.loader.AnalyserLoader workspace path: /home/spring
2022-10-11 17:21:16.443 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient - [SCANNER] o.a.s.ctl.loader.AnalyserLoader analyser install path: /home/spring/dependencies/analysers
2022-10-11 17:21:16.445 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient - [SCANNER] o.a.s.ctl.loader.AnalyserLoader analyser: rule-webapi - [2.0.0-beta.2] is installed
2022-10-11 17:21:16.452 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient - [SCANNER] o.a.scanner.ctl.loader.SlotHubImpl register slot: rule-webapi
2022-10-11 17:21:16.452 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient - [SCANNER] o.a.s.ctl.loader.AnalyserLoader workspace path: /home/spring
2022-10-11 17:21:16.453 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient - [SCANNER] o.a.s.ctl.loader.AnalyserLoader analyser install path: /home/spring/dependencies/analysers
2022-10-11 17:21:16.458 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient - [SCANNER] o.a.s.ctl.loader.AnalyserLoader analyser: rule-test - [2.0.0-beta.2] is installed
2022-10-11 17:21:16.463 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient - [SCANNER] o.a.scanner.ctl.loader.SlotHubImpl register slot: rule-test
2022-10-11 17:21:16.464 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient - [SCANNER] o.a.s.ctl.loader.AnalyserLoader workspace path: /home/spring
2022-10-11 17:21:16.464 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient - [SCANNER] o.a.s.ctl.loader.AnalyserLoader analyser install path: /home/spring/dependencies/analysers
2022-10-11 17:21:16.464 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient - [SCANNER] o.a.s.ctl.loader.AnalyserLoader analyser: rule-sql - [2.0.0-beta.2] is installed
2022-10-11 17:21:16.469 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient - [SCANNER] o.a.scanner.ctl.loader.SlotHubImpl register slot: rule-sql
2022-10-11 17:21:16.490 [DefaultDispatcher-worker-4] INFO  c.t.a.s.infra.ScannerCliClient - [SCANNER] org.archguard.scanner.ctl.Runner <cli parameters>
2022-10-11 17:21:16.491 [DefaultDispatcher-worker-4] INFO  c.t.a.s.infra.ScannerCliClient - |type: SCA
2022-10-11 17:21:16.491 [DefaultDispatcher-worker-4] INFO  c.t.a.s.infra.ScannerCliClient - |systemId: 2
2022-10-11 17:21:16.491 [DefaultDispatcher-worker-4] INFO  c.t.a.s.infra.ScannerCliClient - |serverUrl: http://localhost:8080
2022-10-11 17:21:16.491 [DefaultDispatcher-worker-4] INFO  c.t.a.s.infra.ScannerCliClient - |workspace: /tmp/archguard16869049267192936151
2022-10-11 17:21:16.491 [DefaultDispatcher-worker-4] INFO  c.t.a.s.infra.ScannerCliClient - |path: /tmp/archguard16869049267192936151
2022-10-11 17:21:16.491 [DefaultDispatcher-worker-4] INFO  c.t.a.s.infra.ScannerCliClient - |output: [http]
2022-10-11 17:21:16.491 [DefaultDispatcher-worker-4] INFO  c.t.a.s.infra.ScannerCliClient - <customized analysers>
2022-10-11 17:21:16.491 [DefaultDispatcher-worker-4] INFO  c.t.a.s.infra.ScannerCliClient - |analyzerSpec: []
2022-10-11 17:21:16.491 [DefaultDispatcher-worker-4] INFO  c.t.a.s.infra.ScannerCliClient - |slotSpec: []
2022-10-11 17:21:16.491 [DefaultDispatcher-worker-4] INFO  c.t.a.s.infra.ScannerCliClient - <additional parameters>
2022-10-11 17:21:16.491 [DefaultDispatcher-worker-4] INFO  c.t.a.s.infra.ScannerCliClient - |language: kotlin
2022-10-11 17:21:16.491 [DefaultDispatcher-worker-4] INFO  c.t.a.s.infra.ScannerCliClient - |features: []
2022-10-11 17:21:16.491 [DefaultDispatcher-worker-4] INFO  c.t.a.s.infra.ScannerCliClient - |repoId: null
2022-10-11 17:21:16.491 [DefaultDispatcher-worker-4] INFO  c.t.a.s.infra.ScannerCliClient - |branch: master
2022-10-11 17:21:16.491 [DefaultDispatcher-worker-4] INFO  c.t.a.s.infra.ScannerCliClient - |startedAt: 0
2022-10-11 17:21:16.491 [DefaultDispatcher-worker-4] INFO  c.t.a.s.infra.ScannerCliClient - |since: null
2022-10-11 17:21:16.491 [DefaultDispatcher-worker-4] INFO  c.t.a.s.infra.ScannerCliClient - |until: null
2022-10-11 17:21:16.491 [DefaultDispatcher-worker-4] INFO  c.t.a.s.infra.ScannerCliClient - |depth: 7
2022-10-11 17:21:16.491 [DefaultDispatcher-worker-4] INFO  c.t.a.s.infra.ScannerCliClient - |rules: []
2022-10-11 17:21:16.544 [DefaultDispatcher-worker-4] INFO  c.t.a.s.infra.ScannerCliClient - [SCANNER] o.a.s.ctl.loader.AnalyserLoader workspace path: /home/spring
2022-10-11 17:21:16.546 [DefaultDispatcher-worker-4] INFO  c.t.a.s.infra.ScannerCliClient - [SCANNER] o.a.s.ctl.loader.AnalyserLoader analyser install path: /home/spring/dependencies/analysers
2022-10-11 17:21:16.557 [DefaultDispatcher-worker-4] INFO  c.t.a.s.infra.ScannerCliClient - [SCANNER] o.a.s.ctl.loader.AnalyserLoader analyser: sca - [2.0.0-beta.2] is installed
2022-10-11 17:21:16.658 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient - [SCANNER] o.a.s.ctl.loader.AnalyserLoader workspace path: /home/spring
2022-10-11 17:21:16.658 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient - [SCANNER] o.a.s.ctl.loader.AnalyserLoader analyser install path: /home/spring/dependencies/analysers
2022-10-11 17:21:16.658 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient - [SCANNER] o.a.s.ctl.loader.AnalyserLoader analyser: kotlin - [2.0.0-beta.2] is installed
2022-10-11 17:21:16.728 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient - Exception in thread "main" java.lang.NoSuchMethodError: java.util.stream.Stream.toList()Ljava/util/List;
2022-10-11 17:21:16.728 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient - 	at org.archguard.scanner.core.sourcecode.LanguageSourceCodeAnalyser$DefaultImpls.getFilesByPath(LanguageSourceCodeAnalyser.kt:18)
2022-10-11 17:21:16.733 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient - 	at org.archguard.scanner.analyser.KotlinAnalyser.getFilesByPath(KotlinAnalyser.kt:13)
2022-10-11 17:21:16.735 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient - 	at org.archguard.scanner.analyser.KotlinAnalyser$analyse$1.invokeSuspend(KotlinAnalyser.kt:19)
2022-10-11 17:21:16.738 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient - 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2022-10-11 17:21:16.740 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient - 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2022-10-11 17:21:16.740 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient - 	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:279)
2022-10-11 17:21:16.740 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient - 	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
2022-10-11 17:21:16.740 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient - 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
2022-10-11 17:21:16.740 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient - 	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
2022-10-11 17:21:16.740 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient - 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
2022-10-11 17:21:16.740 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient - 	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
2022-10-11 17:21:16.740 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient - 	at org.archguard.scanner.analyser.KotlinAnalyser.analyse(KotlinAnalyser.kt:17)
2022-10-11 17:21:16.740 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient - 	at org.archguard.scanner.core.sourcecode.LanguageSourceCodeAnalyser$DefaultImpls.analyse(LanguageSourceCodeAnalyser.kt:10)
2022-10-11 17:21:16.740 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient - 	at org.archguard.scanner.analyser.KotlinAnalyser.analyse(KotlinAnalyser.kt:13)
2022-10-11 17:21:16.740 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient - 	at org.archguard.scanner.ctl.loader.SourceCodeWorker$run$1.invokeSuspend(AnalyserDispatcher.kt:71)
2022-10-11 17:21:16.740 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient - 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2022-10-11 17:21:16.740 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient - 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2022-10-11 17:21:16.740 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient - 	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:279)
2022-10-11 17:21:16.740 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient - 	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
2022-10-11 17:21:16.740 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient - 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
2022-10-11 17:21:16.740 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient - 	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
2022-10-11 17:21:16.740 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient - 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
2022-10-11 17:21:16.740 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient - 	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
2022-10-11 17:21:16.741 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient - 	at org.archguard.scanner.ctl.loader.SourceCodeWorker.run(AnalyserDispatcher.kt:69)
2022-10-11 17:21:16.741 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient - 	at org.archguard.scanner.ctl.loader.AnalyserDispatcher.dispatch(AnalyserDispatcher.kt:34)
2022-10-11 17:21:16.741 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient - 	at org.archguard.scanner.ctl.Runner.run(Runner.kt:92)
2022-10-11 17:21:16.741 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient - 	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:198)
2022-10-11 17:21:16.741 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient - 	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:18)
2022-10-11 17:21:16.741 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient - 	at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:395)
2022-10-11 17:21:16.741 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient - 	at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:392)
2022-10-11 17:21:16.741 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient - 	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:410)
2022-10-11 17:21:16.751 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient - 	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:435)
2022-10-11 17:21:16.757 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient - 	at org.archguard.scanner.ctl.RunnerKt.main(Runner.kt:96)
2022-10-11 17:21:17.358 [DefaultDispatcher-worker-4] INFO  c.t.a.s.infra.ScannerCliClient - [SCANNER] o.a.s.ctl.client.ArchGuardHttpClient process topic: sca-dependencies
2022-10-11 17:21:18.365 [http-nio-8080-exec-4] DEBUG c.t.a.s.repository.ScaRepository - clean up old data for systemId: 2
2022-10-11 17:21:18.367 [http-nio-8080-exec-4] DEBUG c.t.a.s.repository.ScaRepository - save new data for systemId: 2
2022-10-11 17:21:18.519 [http-nio-8080-exec-4] DEBUG c.t.a.s.repository.ScaRepository - save new data for systemId: 2 done
2022-10-11 17:21:18.560 [DefaultDispatcher-worker-4] INFO  c.t.a.s.infra.ScannerCliClient - [SCANNER] o.a.s.ctl.client.ArchGuardHttpClient response status: 200
2022-10-11 17:21:18.560 [DefaultDispatcher-worker-4] INFO  c.t.a.s.infra.ScannerCliClient - response body: 
```

4. 点击代码分析、影响分析等各个页面，内容都是空的，系统也无法选择

**Expected behavior**
产生代码分析结果

**Screenshots**
![image](https://user-images.githubusercontent.com/5786067/195066907-d26ad527-602a-496d-a332-0d80c14b4e5c.png)
![image](https://user-images.githubusercontent.com/5786067/195066978-1fdef629-5912-4f26-833d-30c5bac19a96.png)
![image](https://user-images.githubusercontent.com/5786067/195066829-8cd12f90-2a37-4538-9522-f313403f7431.png)

**Comment by phodal** [comment]
奇怪 了，看上去是没有拿到代码。容器里的 `/tmp/archguard16869049267192936151` 目录下有内容吗？

**Comment by AllenShi** [comment]
代码都下载到了，目录下有git项目的代码。如果下载失败会报错的

**Comment by AllenShi** [comment]
另外，我看FAQ有这么一项。不明白jar包需要什么权限？

通过docker部署：添加系统并点击扫描完成后，发现没有分析结果数据
原因：docker容器中下载的jar包权限不足。

方案：以root身份进入容器，修改/home/spring目录下的jar包权限。

**Comment by phodal** [comment]
有点像是 JDK 版本不对？`Exception in thread "main" java.lang.NoSuchMethodError: java.util.stream.Stream.toList()Ljava/util/List;` 

类似于这个：https://youtrack.jetbrains.com/issue/KT-47039 ？

**Comment by phodal** [comment]
> 另外，我看FAQ有这么一项。不明白jar包需要什么权限？
> 
> 通过docker部署：添加系统并点击扫描完成后，发现没有分析结果数据 原因：docker容器中下载的jar包权限不足。
> 
> 方案：以root身份进入容器，修改/home/spring目录下的jar包权限。

这个是手动复制 jar 进去，才会出现的问题。

**Comment by AllenShi** [comment]
> 有点像是 JDK 版本不对？`Exception in thread "main" java.lang.NoSuchMethodError: java.util.stream.Stream.toList()Ljava/util/List;`
> 
> 类似于这个：https://youtrack.jetbrains.com/issue/KT-47039 ？

运行的JDK是容器的openjdk版本。编译时我看你们的设置是与1.8版本兼容

**Comment by phodal** [comment]
看上面 Kotlin 编译器上面的 bug 好像是没有修复的 —— 虽然设计了 1.8 ，但是编译器有问题，所以还是不行。
