### ISSUE TITLE
扫描代码报错

### ISSUE THREAD

**Issue by luodanqing** [archguard/archguard#122]
```
2022-11-23 08:32:44.429 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - [SCANNER] o.a.s.a.xml.XmlParser$Companion org.xml.sax.SAXParseExceptionpublicId: -//Puppy Crawl//DTD Check Configuration 1.3//EN; systemId: http://checkstyle.org/dtds/configuration_1_3.dtd; lineNumber: 1; columnNumber: 2; The markup declarations contained or pointed to by the document type declaration must be well-formed.
2022-11-23 08:32:44.434 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - [SCANNER] o.a.s.ctl.client.ArchGuardHttpClient process topic: datamap-relations
2022-11-23 08:32:44.441 [http-nio-8080-exec-5] INFO  c.t.a.s.c.ScannerReportingService - ========================================================
2022-11-23 08:32:44.441 [http-nio-8080-exec-5] INFO  c.t.a.s.c.ScannerReportingService - delete data_code_database_relation spend 0
2022-11-23 08:32:44.441 [pool-2-thread-5] INFO  c.t.a.i.task.SqlExecuteRunnable - thread-data_code_database_relation is running
2022-11-23 08:32:44.442 [http-nio-8080-exec-5] INFO  c.t.a.s.c.ScannerReportingService - ============ system 1 clean db is done ==============
2022-11-23 08:32:44.443 [http-nio-8080-exec-5] INFO  c.t.a.s.c.ScannerReportingService - ============ system 1 insert db is done ==============
2022-11-23 08:32:44.443 [http-nio-8080-exec-5] INFO  c.t.a.s.c.ScannerReportingService - ============ system 1 update db is done ==============
2022-11-23 08:32:44.443 [http-nio-8080-exec-5] INFO  c.t.a.s.c.ScannerReportingService - ========================================================
2022-11-23 08:32:44.447 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - [SCANNER] o.a.s.ctl.client.ArchGuardHttpClient response status: 200
2022-11-23 08:32:44.447 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - response body: 
2022-11-23 08:32:44.496 [DefaultDispatcher-worker-4] INFO  c.t.a.s.infra.ScannerCliClient - [SCANNER] o.a.s.ctl.client.ArchGuardHttpClient response status: 200
2022-11-23 08:32:44.496 [DefaultDispatcher-worker-4] INFO  c.t.a.s.infra.ScannerCliClient - response body: 
2022-11-23 08:32:45.699 [pool-1-thread-4] INFO  c.t.a.s.domain.service.DitService - Finish calculate all DepthOfInheritance, count: 700
2022-11-23 08:32:47.128 [pool-1-thread-4] INFO  c.t.a.s.domain.service.NocService - Finish calculate all noc, count: 700
2022-11-23 08:33:07.618 [pool-1-thread-4] INFO  c.t.a.s.domain.service.LCOM4Service - Finish calculate all lcom4, count: 700
2022-11-23 08:33:07.657 [pool-1-thread-4] INFO  c.t.a.s.i.m.ClassMetricRepositoryImpl - Delete system class metric old data with id: 1
2022-11-23 08:33:07.712 [pool-1-thread-4] INFO  c.t.a.s.i.m.ClassMetricRepositoryImpl - Insert system class metric new data with id: 1
2022-11-23 08:33:07.712 [pool-1-thread-4] INFO  c.t.a.s.a.MetricPersistApplService - -----------------------------------------------------------------------
2022-11-23 08:33:07.712 [pool-1-thread-4] INFO  c.t.a.s.a.MetricPersistApplService - Finished persist class Metric to mysql for systemId 1
2022-11-23 08:33:07.712 [pool-1-thread-4] INFO  c.t.a.s.a.MetricPersistApplService - -----------------------------------------------------------------------
2022-11-23 08:33:07.781 [pool-1-thread-4] INFO  c.t.a.s.a.MetricPersistApplService - Finished persist moduleCircularDependency in systemId 1
2022-11-23 08:33:07.873 [pool-1-thread-4] INFO  c.t.a.s.a.MetricPersistApplService - Finished persist packageCircularDependency in systemId 1
2022-11-23 08:33:08.084 [pool-1-thread-4] INFO  c.t.a.s.a.MetricPersistApplService - Finished persist classCircularDependency in systemId 1
2022-11-23 08:33:08.276 [pool-1-thread-4] INFO  c.t.a.s.a.MetricPersistApplService - Finished persist methodCircularDependency in systemId 1
2022-11-23 08:33:08.276 [pool-1-thread-4] INFO  c.t.a.s.a.MetricPersistApplService - -----------------------------------------------------------------------
2022-11-23 08:33:08.276 [pool-1-thread-4] INFO  c.t.a.s.a.MetricPersistApplService - Finished persist circularDependenciesCount for systemId 1
2022-11-23 08:33:08.276 [pool-1-thread-4] INFO  c.t.a.s.a.MetricPersistApplService - -----------------------------------------------------------------------
2022-11-23 08:33:17.889 [pool-1-thread-4] INFO  c.t.a.s.a.MetricPersistApplService - -----------------------------------------------------------------------
2022-11-23 08:33:17.889 [pool-1-thread-4] INFO  c.t.a.s.a.MetricPersistApplService - Finished persist data class Metric for systemId 1
2022-11-23 08:33:17.889 [pool-1-thread-4] INFO  c.t.a.s.a.MetricPersistApplService - -----------------------------------------------------------------------
2022-11-23 08:34:03.786 [pool-1-thread-4] INFO  c.t.a.s.i.client.Scanner2Client - send metrics analysis request to module service
2022-11-23 08:34:03.786 [pool-1-thread-4] INFO  c.t.a.s.d.a.ArchitectureDependencyAnalysis - ************************************
2022-11-23 08:34:03.786 [pool-1-thread-4] INFO  c.t.a.s.d.a.ArchitectureDependencyAnalysis -  Finished level 2 analysis metrics
2022-11-23 08:34:03.786 [pool-1-thread-4] INFO  c.t.a.s.d.a.ArchitectureDependencyAnalysis - ************************************
2022-11-23 08:34:05.594 [http-nio-8080-exec-7] ERROR c.t.a.m.i.influx.InfluxDBClient - Client exception when send metrics to InfluxDB. {}
org.springframework.web.client.HttpClientErrorException$BadRequest: 400 Bad Request: "{"error":"partial write: unable to parse 'metric_class_coupling,class_name=.ConsulRegistryServiceTest,package_name=,module_name=root,system_id=1 inner_fan_in=0,inner_fan_out=0,outer_fan_in=0,outer_fan_out=0,inner_instability=0.0,inner_coupling=0.0,outer_instability=0.0,outer_coupling=0.0': missing tag value dropped=0"}<EOL>"
        at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:101)
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:168)
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:122)
        at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
        at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:819)
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:777)
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:711)
        at org.springframework.web.client.RestTemplate.postForObject(RestTemplate.java:437)
        at com.thoughtworks.archguard.metrics.infrastructure.influx.InfluxDBClient.save(InfluxDBClient.kt:19)
        at com.thoughtworks.archguard.metrics.infrastructure.MetricsRepositoryImpl.insertAllClassCouplings(MetricsRepositoryImpl.kt:24)
        at com.thoughtworks.archguard.metrics.infrastructure.MetricsRepositoryImpl$$FastClassBySpringCGLIB$$b2127064.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
        at com.thoughtworks.archguard.metrics.infrastructure.MetricsRepositoryImpl$$EnhancerBySpringCGLIB$$9a26562a.insertAllClassCouplings(<generated>)
        at com.thoughtworks.archguard.metrics.domain.coupling.CouplingServiceImpl.persistAllClassCouplingResults(CouplingServiceImpl.kt:24)
        at com.thoughtworks.archguard.code.module.domain.LogicModuleService.autoDefineLogicModule(LogicModuleService.kt:62)
        at com.thoughtworks.archguard.code.module.controller.LogicModuleController.autoDefineLogicModule(LogicModuleController.kt:90)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:681)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1743)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:835)
````

**Comment by phodal** [comment]
问题还有吗

**Comment by luodanqing** [comment]
> 问题还有吗
用2.0版本还是会有这个问题， 1.6版本没有这个问题
