### ISSUE TITLE
扫描 TypeScript 时，Scanner 出错

### ISSUE THREAD

**Issue by chenhhhhhhhhh** [archguard/archguard#125]
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/95460130/213068619-1765e8b1-b4b0-4b7b-9b67-9712b5e0b9cc.png">

2023-01-18 10:34:48 2023-01-18 10:34:48.935 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient - parseStmt childType -> :VariableStatementContext
2023-01-18 10:34:48 2023-01-18 10:34:48.935 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient - parseStmt childType -> :IfStatementContext
2023-01-18 10:34:48 2023-01-18 10:34:48.935 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient - parseStmt childType -> :IfStatementContext
2023-01-18 10:34:48 2023-01-18 10:34:48.936 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient - variableToFields -> JSON.parse(globalThis.resData) === ArgumentsExpressionContext
2023-01-18 10:34:48 2023-01-18 10:34:48.936 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient - IdentifierExpressionContext -> others variable decl: require ==== require('../../dwt-result.json')
2023-01-18 10:34:48 2023-01-18 10:34:48.936 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient - parseStmt childType -> :ExpressionStatementContext
2023-01-18 10:34:48 2023-01-18 10:34:48.937 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient - todo -> need support type: ArrowFunctionExpressionContext ==== (testCase)=>{constnumFailingTests=testCase.numFailingTests||'Exec Error';console.info(`| ${testCase.filePath} | ${testCase.author} | ${numFailingTests} |`);}
2023-01-18 10:34:48 2023-01-18 10:34:48.937 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient - parseStmt childType -> :IfStatementContext
2023-01-18 10:34:48 2023-01-18 10:34:48.937 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient - todo -> need support type: AdditiveExpressionContext ==== !!b.testExecError-!!a.testExecError
2023-01-18 10:34:48 2023-01-18 10:34:48.938 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient - parseStmt childType -> :VariableStatementContext
2023-01-18 10:34:48 2023-01-18 10:34:48.938 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient - parseStmt childType -> :ExpressionStatementContext
2023-01-18 10:34:48 2023-01-18 10:34:48.938 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient - variableToFields -> testCase.numFailingTests||'Exec Error' === LogicalOrExpressionContext
2023-01-18 10:34:48 2023-01-18 10:34:48.939 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient - enterVariableDeclaration : LogicalOrExpressionContext === numFailingTests=testCase.numFailingTests||'Exec Error'
2023-01-18 10:34:48 2023-01-18 10:34:48.939 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient - todo -> need support type: LiteralExpressionContext ==== `| ${testCase.filePath} | ${testCase.author} | ${numFailingTests} |`
2023-01-18 10:34:48 2023-01-18 10:34:48.940 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient - parseStmt childType -> :VariableStatementContext
2023-01-18 10:34:48 2023-01-18 10:34:48.940 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient - parseStmt childType -> :VariableStatementContext
2023-01-18 10:34:48 2023-01-18 10:34:48.940 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient - parseStmt childType -> :VariableStatementContext
2023-01-18 10:34:48 2023-01-18 10:34:48.941 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient - variableToFields -> getDwtResult() === ArgumentsExpressionContext
2023-01-18 10:34:48 2023-01-18 10:34:48.942 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient - IdentifierExpressionContext -> others variable decl: parseFailedCase ==== parseFailedCase(dwtResult,publicPath)
2023-01-18 10:34:49 2023-01-18 10:34:49.325 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient - line 7:8 no viable alternative at input '.default'
2023-01-18 10:34:49 2023-01-18 10:34:49.333 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient - line 7:16 mismatched input '=' expecting {'function', 'async'}
2023-01-18 10:34:50 2023-01-18 10:34:50.374 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient - line 176:0 rule expressionStatement failed predicate: {this.notOpenBraceAndNotFunction()}?
2023-01-18 10:34:50 2023-01-18 10:34:50.750 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient - line 202:9 no viable alternative at input '.default'
2023-01-18 10:34:50 2023-01-18 10:34:50.750 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient - line 202:17 mismatched input '=' expecting {'function', 'async'}
2023-01-18 10:34:50 2023-01-18 10:34:50.755 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient - line 207:0 mismatched input '}' expecting {<EOF>, RegularExpressionLiteral, '[', '(', '{', ';', '++', '--', '+', '-', '~', '!', '<', '_', '$', 'null', BooleanLiteral, DecimalLiteral, HexIntegerLiteral, OctalIntegerLiteral, OctalIntegerLiteral2, BinaryIntegerLiteral, 'break', 'do', 'instanceof', 'typeof', 'keyof', 'case', 'else', 'new', 'var', 'catch', 'finally', 'return', 'void', 'continue', 'for', 'switch', 'while', 'debugger', 'function', 'this', 'with', 'default', 'if', 'throw', 'delete', 'in', 'try', 'from', 'readonly', 'async', 'await', 'class', 'enum', 'extends', 'super', 'const', 'export', 'import', 'implements', 'let', 'private', 'public', 'interface', 'package', 'protected', 'static', 'yield', 'any', 'number', 'boolean', 'string', 'type', 'get', 'set', 'namespace', 'require', 'module', 'declare', 'undefined', 'abstract', 'is', '@', Identifier, StringLiteral, BackTick}
2023-01-18 10:34:50 2023-01-18 10:34:50.757 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient - enterExpressionStatement : LiteralExpressionContext
2023-01-18 10:34:50 2023-01-18 10:34:50.757 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient - todo -> need support type: LiteralExpressionContext ==== '__esModule'
2023-01-18 10:34:50 2023-01-18 10:34:50.757 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient - todo -> need support type: ObjectLiteralExpressionContext ==== {value:true}
2023-01-18 10:34:50 2023-01-18 10:34:50.757 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient - enterExpressionStatement -> IdentifierExpressionContext: exports.
2023-01-18 10:34:50 2023-01-18 10:34:50.894 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient - Exception in thread "main" java.lang.NullPointerException
2023-01-18 10:34:50 2023-01-18 10:34:50.894 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient -         at chapi.ast.typescriptast.TypeScriptFullIdentListener.enterFunctionDeclaration(TypeScriptFullIdentListener.kt:425)
2023-01-18 10:34:50 2023-01-18 10:34:50.895 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient -         at chapi.ast.antlr.TypeScriptParser$FunctionDeclarationContext.enterRule(TypeScriptParser.java:10017)
2023-01-18 10:34:50 2023-01-18 10:34:50.895 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient -         at org.antlr.v4.runtime.tree.ParseTreeWalker.enterRule(ParseTreeWalker.java:50)
2023-01-18 10:34:50 2023-01-18 10:34:50.896 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient -         at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:33)
2023-01-18 10:34:50 2023-01-18 10:34:50.897 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient -         at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36)
2023-01-18 10:34:50 2023-01-18 10:34:50.897 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient -         at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36)
2023-01-18 10:34:50 2023-01-18 10:34:50.898 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient -         at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36)
2023-01-18 10:34:50 2023-01-18 10:34:50.898 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient -         at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36)
2023-01-18 10:34:50 2023-01-18 10:34:50.898 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient -         at chapi.ast.typescriptast.TypeScriptAnalyser.analysis(TypeScriptAnalyser.kt:14)
2023-01-18 10:34:50 2023-01-18 10:34:50.898 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient -         at org.archguard.scanner.analyser.TypeScriptAnalyser.analysisByFile(TypeScriptAnalyser.kt:42)
2023-01-18 10:34:50 2023-01-18 10:34:50.898 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient -         at org.archguard.scanner.analyser.TypeScriptAnalyser.access$analysisByFile(TypeScriptAnalyser.kt:12)
2023-01-18 10:34:50 2023-01-18 10:34:50.898 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient -         at org.archguard.scanner.analyser.TypeScriptAnalyser$analyse$1$2$1.invokeSuspend(TypeScriptAnalyser.kt:35)
2023-01-18 10:34:50 2023-01-18 10:34:50.898 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient -         at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2023-01-18 10:34:50 2023-01-18 10:34:50.898 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient -         at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2023-01-18 10:34:50 2023-01-18 10:34:50.898 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient -         at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:279)
2023-01-18 10:34:50 2023-01-18 10:34:50.898 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient -         at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
2023-01-18 10:34:50 2023-01-18 10:34:50.898 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient -         at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
2023-01-18 10:34:50 2023-01-18 10:34:50.898 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient -         at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
2023-01-18 10:34:50 2023-01-18 10:34:50.898 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient -         at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
2023-01-18 10:34:50 2023-01-18 10:34:50.898 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient -         at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
2023-01-18 10:34:50 2023-01-18 10:34:50.898 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient -         at org.archguard.scanner.analyser.TypeScriptAnalyser.analyse(TypeScriptAnalyser.kt:19)
2023-01-18 10:34:50 2023-01-18 10:34:50.898 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient -         at org.archguard.scanner.core.sourcecode.LanguageSourceCodeAnalyser$DefaultImpls.analyse(LanguageSourceCodeAnalyser.kt:10)
2023-01-18 10:34:50 2023-01-18 10:34:50.898 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient -         at org.archguard.scanner.analyser.TypeScriptAnalyser.analyse(TypeScriptAnalyser.kt:12)
2023-01-18 10:34:50 2023-01-18 10:34:50.898 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient -         at org.archguard.scanner.ctl.loader.SourceCodeWorker$run$1.invokeSuspend(AnalyserDispatcher.kt:71)
2023-01-18 10:34:50 2023-01-18 10:34:50.899 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient -         at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2023-01-18 10:34:50 2023-01-18 10:34:50.899 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient -         at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2023-01-18 10:34:50 2023-01-18 10:34:50.899 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient -         at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:279)
2023-01-18 10:34:50 2023-01-18 10:34:50.899 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient -         at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
2023-01-18 10:34:50 2023-01-18 10:34:50.899 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient -         at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
2023-01-18 10:34:50 2023-01-18 10:34:50.899 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient -         at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
2023-01-18 10:34:50 2023-01-18 10:34:50.899 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient -         at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
2023-01-18 10:34:50 2023-01-18 10:34:50.899 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient -         at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
2023-01-18 10:34:50 2023-01-18 10:34:50.899 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient -         at org.archguard.scanner.ctl.loader.SourceCodeWorker.run(AnalyserDispatcher.kt:69)
2023-01-18 10:34:50 2023-01-18 10:34:50.899 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient -         at org.archguard.scanner.ctl.loader.AnalyserDispatcher.dispatch(AnalyserDispatcher.kt:34)
2023-01-18 10:34:50 2023-01-18 10:34:50.899 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient -         at org.archguard.scanner.ctl.Runner.run(Runner.kt:92)
2023-01-18 10:34:50 2023-01-18 10:34:50.899 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient -         at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:198)
2023-01-18 10:34:50 2023-01-18 10:34:50.899 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient -         at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:18)
2023-01-18 10:34:50 2023-01-18 10:34:50.899 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient -         at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:395)
2023-01-18 10:34:50 2023-01-18 10:34:50.899 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient -         at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:392)
2023-01-18 10:34:50 2023-01-18 10:34:50.906 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient -         at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:410)
2023-01-18 10:34:50 2023-01-18 10:34:50.906 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient -         at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:435)
2023-01-18 10:34:50 2023-01-18 10:34:50.906 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient -         at org.archguard.scanner.ctl.RunnerKt.main(Runner.kt:96)
2023-01-18 10:35:07 2023-01-18 10:35:07.125 [DefaultDispatcher-worker-4] ERROR c.a.druid.filter.stat.StatFilter - slow sql 6924 millis. insert into scm_git_hot_file (system_id, repo, path, module_name, class_name, modified_count, jclass_id) values (?, ?, ?, ?, ?, ?, ?)[2,"https://git.woa.com/tencent-doc-core/melo.git","warning: you may want to set your diff.renameLimit variable to at least 1764 and retry the command.",null,null,1,null]
2023-01-18 10:35:07 2023-01-18 10:35:07.126 [DefaultDispatcher-worker-4] INFO  c.t.a.s.d.s.git.GitHotFileScanner - Saved gitHotFiles, systemId=2
2023-01-18 10:38:02 2023-01-18 10:38:02.426 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient - [SCANNER] o.a.s.ctl.client.ArchGuardHttpClient process topic: git-logs
2023-01-18 10:38:06 2023-01-18 10:38:06.116 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient - Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
2023-01-18 10:38:06 2023-01-18 10:38:06.119 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient -         at java.base/java.util.Arrays.copyOf(Arrays.java:3842)
2023-01-18 10:38:06 2023-01-18 10:38:06.119 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient -         at kotlinx.serialization.json.internal.JsonStringBuilder.ensureTotalCapacity(JsonStringBuilder.kt:128)
2023-01-18 10:38:06 2023-01-18 10:38:06.119 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient -         at kotlinx.serialization.json.internal.JsonStringBuilder.ensureAdditionalCapacity(JsonStringBuilder.kt:121)
2023-01-18 10:38:06 2023-01-18 10:38:06.119 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient -         at kotlinx.serialization.json.internal.JsonStringBuilder.appendQuoted(JsonStringBuilder.kt:51)
2023-01-18 10:38:06 2023-01-18 10:38:06.119 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient -         at kotlinx.serialization.json.internal.Composer.printQuoted(Composers.kt:41)
2023-01-18 10:38:06 2023-01-18 10:38:06.119 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient -         at kotlinx.serialization.json.internal.StreamingJsonEncoder.encodeString(StreamingJsonEncoder.kt:211)
2023-01-18 10:38:06 2023-01-18 10:38:06.119 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient -         at kotlinx.serialization.json.internal.StreamingJsonEncoder.encodeElement(StreamingJsonEncoder.kt:142)
2023-01-18 10:38:06 2023-01-18 10:38:06.119 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient -         at kotlinx.serialization.encoding.AbstractEncoder.encodeIntElement(AbstractEncoder.kt:60)
2023-01-18 10:38:06 2023-01-18 10:38:06.119 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient -         at org.archguard.scanner.core.git.ChangeEntry.write$Self(GitLogs.kt:22)
2023-01-18 10:38:06 2023-01-18 10:38:06.119 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient -         at org.archguard.scanner.core.git.ChangeEntry$$serializer.serialize(GitLogs.kt:22)
2023-01-18 10:38:06 2023-01-18 10:38:06.119 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient -         at org.archguard.scanner.core.git.ChangeEntry$$serializer.serialize(GitLogs.kt:22)
2023-01-18 10:38:06 2023-01-18 10:38:06.119 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient -         at kotlinx.serialization.json.internal.StreamingJsonEncoder.encodeSerializableValue(StreamingJsonEncoder.kt:219)
2023-01-18 10:38:06 2023-01-18 10:38:06.119 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient -         at kotlinx.serialization.encoding.AbstractEncoder.encodeSerializableElement(AbstractEncoder.kt:80)
2023-01-18 10:38:06 2023-01-18 10:38:06.119 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient -         at kotlinx.serialization.internal.ListLikeSerializer.serialize(CollectionSerializers.kt:69)
2023-01-18 10:38:06 2023-01-18 10:38:06.119 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient -         at kotlinx.serialization.json.internal.StreamingJsonEncoder.encodeSerializableValue(StreamingJsonEncoder.kt:219)
2023-01-18 10:38:06 2023-01-18 10:38:06.119 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient -         at kotlinx.serialization.encoding.AbstractEncoder.encodeSerializableElement(AbstractEncoder.kt:80)
2023-01-18 10:38:06 2023-01-18 10:38:06.120 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient -         at org.archguard.scanner.core.git.GitLogs.write$Self(GitLogs.kt:5)
2023-01-18 10:38:06 2023-01-18 10:38:06.120 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient -         at org.archguard.scanner.core.git.GitLogs$$serializer.serialize(GitLogs.kt:5)
2023-01-18 10:38:06 2023-01-18 10:38:06.120 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient -         at org.archguard.scanner.core.git.GitLogs$$serializer.serialize(GitLogs.kt:5)
2023-01-18 10:38:06 2023-01-18 10:38:06.120 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient -         at kotlinx.serialization.json.internal.StreamingJsonEncoder.encodeSerializableValue(StreamingJsonEncoder.kt:219)
2023-01-18 10:38:06 2023-01-18 10:38:06.120 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient -         at kotlinx.serialization.encoding.AbstractEncoder.encodeSerializableElement(AbstractEncoder.kt:80)
2023-01-18 10:38:06 2023-01-18 10:38:06.120 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient -         at kotlinx.serialization.internal.ListLikeSerializer.serialize(CollectionSerializers.kt:69)
2023-01-18 10:38:06 2023-01-18 10:38:06.120 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient -         at kotlinx.serialization.json.internal.StreamingJsonEncoder.encodeSerializableValue(StreamingJsonEncoder.kt:219)
2023-01-18 10:38:06 2023-01-18 10:38:06.120 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient -         at kotlinx.serialization.json.Json.encodeToString(Json.kt:85)
2023-01-18 10:38:06 2023-01-18 10:38:06.120 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient -         at org.archguard.scanner.ctl.client.ArchGuardHttpClient.saveGitLogs(ArchGuardHttpClient.kt:183)
2023-01-18 10:38:06 2023-01-18 10:38:06.120 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient -         at org.archguard.scanner.ctl.client.ChainedArchGuardClient.saveGitLogs(ChainedArchGuardClient.kt:18)
2023-01-18 10:38:06 2023-01-18 10:38:06.120 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient -         at org.archguard.scanner.analyser.GitAnalyser.analyse(GitAnalyser.kt:13)
2023-01-18 10:38:06 2023-01-18 10:38:06.120 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient -         at org.archguard.scanner.ctl.loader.GitWorker.run(AnalyserDispatcher.kt:96)
2023-01-18 10:38:06 2023-01-18 10:38:06.120 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient -         at org.archguard.scanner.ctl.loader.AnalyserDispatcher.dispatch(AnalyserDispatcher.kt:34)
2023-01-18 10:38:06 2023-01-18 10:38:06.120 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient -         at org.archguard.scanner.ctl.Runner.run(Runner.kt:92)
2023-01-18 10:38:06 2023-01-18 10:38:06.120 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient -         at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:198)
2023-01-18 10:38:06 2023-01-18 10:38:06.120 [DefaultDispatcher-worker-3] INFO  c.t.a.s.infra.ScannerCliClient -         at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:18)

**Comment by phodal** [comment]
能提供一下导致错误的文件吗？
