### ISSUE TITLE
Invalid or corrupt jarfile scanner_cli.jar

### ISSUE THREAD

**Issue by ariesfly** [archguard/archguard#127]
相关日志：

2023-02-15 15:40:39.840 [pool-1-thread-1] INFO  c.t.a.s.i.command.Processor - Updating files: 100% (1682/1682), done.
2023-02-15 15:40:43.847 [DefaultDispatcher-worker-4] INFO  c.t.a.s.infra.ScannerCliClient - Error: Invalid or corrupt jarfile scanner_cli.jar
2023-02-15 15:40:43.893 [DefaultDispatcher-worker-1] INFO  c.t.a.s.infra.ScannerCliClient - Error: Invalid or corrupt jarfile scanner_cli.jar
2023-02-15 15:40:59.189 [DefaultDispatcher-worker-5] ERROR c.a.druid.filter.stat.StatFilter - slow sql 2695 millis. insert into scm_git_hot_file (system_id, repo, path, module_name, class_name, modified_count, jclass_id) values (?, ?, ?, ?, ?, ?, ?)[3,"https://github.com/archguard/archguard.git","scan_git/src/main/resources/logbak.xml","scan_git",null,1,null]
2023-02-15 15:40:59.205 [DefaultDispatcher-worker-5] INFO  c.t.a.s.d.s.git.GitHotFileScanner - Saved gitHotFiles, systemId=3

求解

**Comment by phodal** [comment]
看看这个 jar 是不是正常的？诸如于：检查从 GitHub 的下载情况？

**Comment by ariesfly** [comment]
断点了下，可以下载 ，isInstalled(fileName) 返回时 true

**Comment by phodal** [comment]
isInstalled 是 spec 里的，是需要其它 jar 的，比如 ` lang_csharp-2.0.0-beta.2-all.jar ` 之类的

**Comment by ariesfly** [comment]
有什么日志会有打印出来，看下具体信息么？

**Comment by phodal** [comment]
```bash
[SCANNER] o.a.s.ctl.loader.AnalyserLoader workspace path: /home/parallels/Desktop/demo
[SCANNER] o.a.s.ctl.loader.AnalyserLoader analyser install path: /home/parallels/Desktop/demo/dependencies/analysers
[SCANNER] o.a.s.ctl.loader.AnalyserLoader analyser: rule-webapi - [2.0.0-beta.5] is installed
[SCANNER] o.a.scanner.ctl.loader.SlotHubImpl register slot: rule-webapi
[SCANNER] o.a.s.ctl.loader.AnalyserLoader workspace path: /home/parallels/Desktop/demo
[SCANNER] o.a.s.ctl.loader.AnalyserLoader analyser install path: /home/parallels/Desktop/demo/dependencies/analysers
[SCANNER] o.a.s.ctl.loader.AnalyserLoader analyser: rule-test - [2.0.0-beta.5] is installed
[SCANNER] o.a.scanner.ctl.loader.SlotHubImpl register slot: rule-test
[SCANNER] o.a.s.ctl.loader.AnalyserLoader workspace path: /home/parallels/Desktop/demo
[SCANNER] o.a.s.ctl.loader.AnalyserLoader analyser install path: /home/parallels/Desktop/demo/dependencies/analysers
[SCANNER] o.a.s.ctl.loader.AnalyserLoader analyser: rule-sql - [2.0.0-beta.5] is installed
[SCANNER] o.a.scanner.ctl.loader.SlotHubImpl register slot: rule-sql
[SCANNER] o.a.s.ctl.loader.AnalyserLoader workspace path: /home/parallels/Desktop/demo
[SCANNER] o.a.s.ctl.loader.AnalyserLoader analyser install path: /home/parallels/Desktop/demo/dependencies/analysers
[SCANNER] o.a.s.ctl.loader.AnalyserLoader analyser: kotlin - [2.0.0-beta.5] is installed
[SCANNER] o.a.scanner.ctl.loader.SlotHubImpl found output type: chapi.domain.core.CodeDataStruct
[SCANNER] o.a.scanner.ctl.loader.SlotHubImpl try plug slot for: org.archguard.linter.rule.testcode.TestSmellRuleSlot@1f1d416f
[SCANNER] o.a.scanner.ctl.loader.SlotHubImpl done plug slot for: org.archguard.linter.rule.testcode.TestSmellRuleSlot@1f1d416f
[SCANNER] o.a.scanner.ctl.loader.SlotHubImpl found output type: org.archguard.rule.core.Issue
[SCANNER] o.a.s.ctl.loader.AnalyserLoader workspace path: /home/parallels/Desktop/demo
[SCANNER] o.a.s.ctl.loader.AnalyserLoader analyser install path: /home/parallels/Desktop/demo/dependencies/analysers
[SCANNER] o.a.s.ctl.loader.AnalyserLoader analyser: datamap - [2.0.0-beta.5] is installed 
```

**Comment by ariesfly** [comment]
2023-02-15 16:10:56.899 [DefaultDispatcher-worker-2 @coroutine#1] INFO  c.t.a.s.infra.ScannerCliClient - [SCANNER] o.a.s.ctl.client.ArchGuardHttpClient process topic: sca-dependencies
2023-02-15 16:10:56.900 [DefaultDispatcher-worker-2 @coroutine#1] INFO  c.t.a.s.infra.ScannerCliClient - Exception in thread "main" java.net.URISyntaxException: Illegal character in query at index 86: http://localhost:8080/api/scanner/3/reporting/sca-dependencies?language=kotlin&path=C:\Users\zhenlin\AppData\Local\Temp\archguard15652771582882474328
2023-02-15 16:10:56.900 [DefaultDispatcher-worker-2 @coroutine#1] INFO  c.t.a.s.infra.ScannerCliClient - 	at java.base/java.net.URI$Parser.fail(URI.java:2913)

找到了些详细的  Exception in thread "main" java.net.URISyntaxException  这个是什么问题？

**Comment by phodal** [comment]
应该是 Windows 下生成的 path 有问题，导致 new URI 出错了：

https://github.com/archguard/archguard/blob/b06bb8bf7036a8d9cff1cab0204e454cde1b06c2/scanner_cli/src/main/kotlin/org/archguard/scanner/ctl/client/ArchGuardHttpClient.kt#L57-L60

**Comment by ariesfly** [comment]
确实 是windows 环境，这个该如何改下？

**Comment by phodal** [comment]
理论上应该对 path 进行 encode：

https://github.com/archguard/archguard/blob/b06bb8bf7036a8d9cff1cab0204e454cde1b06c2/scanner_cli/src/main/kotlin/org/archguard/scanner/ctl/client/ArchGuardHttpClient.kt#L39-L40

在对应分析 path 的地方进行 decode。

不过，现在运行的方式有点奇怪，理论上 ArchGuard Server 应该是部署在类 Unix 环境下的。如果在 Windows 下运行的话，path 一般是等于 `.` 的。

**Comment by ariesfly** [comment]
目前调研下产品就 本地了，window是麻烦  不过 手上没Mac。 哎

**Comment by phodal** [comment]
这个路径是用来 debug 用的，并不是很重要。你可以

1. 修改本地的 scanner_cli 然后本地构建一下就可以了
2. 或者不用 sca 这种类型的 scanner：

https://github.com/archguard/archguard/blob/b06bb8bf7036a8d9cff1cab0204e454cde1b06c2/server/src/main/kotlin/com/thoughtworks/archguard/smartscanner/StranglerScannerExecutor.kt#L36-L53

**Comment by ariesfly** [comment]
重新构建 注释后 扫描报

2023-02-15 16:47:59.279 [pool-1-thread-1] INFO  c.t.a.s.i.command.Processor - Already up to date.
Exception in thread "DefaultDispatcher-worker-1 @coroutine#1" kotlin.NotImplementedError: An operation is not implemented: deprecated, replace with StranglerScannerExecutor.run(context, SCA)
	at com.thoughtworks.archguard.scanner.domain.scanner.codescan.sca.ScaScanner.scan(ScaScanner.kt:12)
	at com.thoughtworks.archguard.scanner.domain.scanner.codescan.sca.ScaScanner.scan(ScaScanner.kt:7)

另外，同样还是出现了

Exception in thread "main" java.net.URISyntaxException: Illegal character in query at index 78:

**Comment by phodal** [comment]
哈哈，@ariesfly 可以参考上面的提交修复 https://github.com/archguard/archguard/commit/877eaf86b8374e3e578a4c019df92eb3eabf1fe3

**Comment by ariesfly** [comment]
已经解决了 tks
