### ISSUE TITLE
error when scanning :Unauthorized: 401 Unauthorized: "{"code":"unauthorized","message":"unauthorized access"}"] with root cause299936

### ISSUE THREAD

**Issue by architectpub** [archguard/archguard#135]
**Describe the bug**

**Env (please complete the following information):**
 - OS: Windows
 - Env: Local Dev
 - Browser :Chrome
 - Version :2.0.1

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://github.com/archguard/archguard/assets/123437240/d4f755c3-e84c-42ad-b55d-382c50683fb8)

/localhost:3306/archguard, version : 1.2.8, lastPacketReceivedIdleMillis : 295548
2023-06-30 14:54:58.403 [http-nio-8081-exec-9] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.web.client.HttpClientErrorException$Unauthorized: 401 Unauthorized: "{"code":"unauthorized","message":"unauthorized access"}"] with root cause
org.springframework.web.client.HttpClientErrorException$Unauthorized: 401 Unauthorized: "{"code":"unauthorized","message":"unauthorized access"}"
        at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:105)
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:168)
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:122)
        at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
        at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:825)
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:783)
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:717)
        at org.springframework.web.client.RestTemplate.getForEntity(RestTemplate.java:367)
        at com.thoughtworks.archguard.metrics.infrastructure.influx.InfluxDBClient.query(InfluxDBClient.kt:41)
        at com.thoughtworks.archguard.insights.InsightController.listInsights(InsightController.kt:71)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)

**Additional context**

**Comment by phodal** [comment]
duplicated https://github.com/archguard/archguard/issues/85
