### ISSUE TITLE
error when  sca-dependencies in windows for  Illegal character in query at index 

### ISSUE THREAD

**Issue by architectpub** [archguard/archguard#136]
**Describe the bug**

error when  sca-dependencies in windows for  Illegal character in query at index 

**Env (please complete the following information):**
 - OS: Windows
 - Env: Local Dev
 - Browser: chrome
 - Version :2.0.1

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://github.com/archguard/archguard/assets/123437240/e3588aae-1059-446c-90af-5abdc9e50767)

2023-07-02 08:41:25.652 [DefaultDispatcher-worker-1] INFO  c.t.a.s.infra.ScannerCliClient - [SCANNER] o.a.s.ctl.client.ArchGuardHttpClient process topic: sca-dependencies
2023-07-02 08:41:25.653 [DefaultDispatcher-worker-1] INFO  c.t.a.s.infra.ScannerCliClient - Exception in thread "main" java.net.URISyntaxException: Illegal character in query at index 84: http://localhost:8081/api/scanner/2/reporting/sca-dependencies?language=java&path=C:\Users\hanhw1\AppData\Local\Temp\archguard16829624270070083663
2023-07-02 08:41:25.654 [DefaultDispatcher-worker-1] INFO  c.t.a.s.infra.ScannerCliClient -     at java.base/java.net.URI$Parser.fail(URI.java:2974)
2023-07-02 08:41:25.654 [DefaultDispatcher-worker-1] INFO  c.t.a.s.infra.ScannerCliClient -     at java.base/java.net.URI$Parser.checkChars(URI.java:3145)
2023-07-02 08:41:25.654 [DefaultDispatcher-worker-1] INFO  c.t.a.s.infra.ScannerCliClient -     at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3233)
2023-07-02 08:41:25.654 [DefaultDispatcher-worker-1] INFO  c.t.a.s.infra.ScannerCliClient -     at java.base/java.net.URI$Parser.parse(URI.java:3175)
2023-07-02 08:41:25.654 [DefaultDispatcher-worker-1] INFO  c.t.a.s.infra.ScannerCliClient -     at java.base/java.net.URI.<init>(URI.java:623)
2023-07-02 08:41:25.654 [DefaultDispatcher-worker-1] INFO  c.t.a.s.infra.ScannerCliClient -     at org.archguard.scanner.ctl.client.ArchGuardHttpClient.saveDependencies(ArchGuardHttpClient.kt:219)
2023-07-02 08:41:25.654 [DefaultDispatcher-worker-1] INFO  c.t.a.s.infra.ScannerCliClient -     at org.archguard.scanner.ctl.client.ChainedArchGuardClient.saveDependencies(ChainedArchGuardClient.kt:21)
2023-07-02 08:41:25.654 [DefaultDispatcher-worker-1] INFO  c.t.a.s.infra.ScannerCliClient -     at org.archguard.scanner.analyser.ScaAnalyser.analyse(ScaAnalyser.kt:33)
2023-07-02 08:41:25.655 [DefaultDispatcher-worker-1] INFO  c.t.a.s.infra.ScannerCliClient -     at org.archguard.scanner.ctl.loader.ScaWorker.run(AnalyserDispatcher.kt:123)
2023-07-02 08:41:25.655 [DefaultDispatcher-worker-1] INFO  c.t.a.s.infra.ScannerCliClient -     at org.archguard.scanner.ctl.loader.AnalyserDispatcher.dispatch(AnalyserDispatcher.kt:34)
2023-07-02 08:41:25.655 [DefaultDispatcher-worker-1] INFO  c.t.a.s.infra.ScannerCliClient -     at org.archguard.scanner.ctl.Runner.run(Runner.kt:92)
2023-07-02 08:41:25.655 [DefaultDispatcher-worker-1] INFO  c.t.a.s.infra.ScannerCliClient -     at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:198)
2023-07-02 08:41:25.655 [DefaultDispatcher-worker-1] INFO  c.t.a.s.infra.ScannerCliClient -     at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:18)
2023-07-02 08:41:25.655 [DefaultDispatcher-worker-1] INFO  c.t.a.s.infra.ScannerCliClient -     at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:395)
2023-07-02 08:41:25.655 [DefaultDispatcher-worker-1] INFO  c.t.a.s.infra.ScannerCliClient -     at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:392)
2023-07-02 08:41:25.655 [DefaultDispatcher-worker-1] INFO  c.t.a.s.infra.ScannerCliClient -     at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:410)
2023-07-02 08:41:25.655 [DefaultDispatcher-worker-1] INFO  c.t.a.s.infra.ScannerCliClient -     at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:435)
2023-07-02 08:41:25.656 [DefaultDispatcher-worker-1] INFO  c.t.a.s.infra.ScannerCliClient -     at org.archguard.scanner.ctl.RunnerKt.main(Runner.kt:96)
2023-07-02 08:41:26.697 [DefaultDispatcher-worker-4] INFO  c.t.a.s.infra.ScannerCliClient - [SCANNER] o.a.s.ctl.client.ArchGuardHttpClient process topic: class-items
2023-07-02 08:41:26.698 [DefaultDispatcher-worker-4] INFO  c.t.a.s.infra.ScannerCliClient - Exception in thread "main" java.net.URISyntaxException: Illegal character in query at index 79: http://localhost:8081/api/scanner/2/reporting/class-items?language=java&path=C:\Users\hanhw1\AppData\Local\Temp\archguard16829624270070083663
2023-07-02 08:41:26.699 [DefaultDispatcher-worker-4] INFO  c.t.a.s.infra.ScannerCliClient -     at java.base/java.net.URI$Parser.fail(URI.java:2974)
2023-07-02 08:41:26.699 [DefaultDispatcher-worker-4] INFO  c.t.a.s.infra.ScannerCliClient -     at java.base/java.net.URI$Parser.checkChars(URI.java:3145)
2023-07-02 08:41:26.699 [DefaultDispatcher-worker-4] INFO  c.t.a.s.infra.ScannerCliClient -     at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3233)
2023-07-02 08:41:26.699 [DefaultDispatcher-worker-4] INFO  c.t.a.s.infra.ScannerCliClient -     at java.base/java.net.URI$Parser.parse(URI.java:3175)
2023-07-02 08:41:26.699 [DefaultDispatcher-worker-4] INFO  c.t.a.s.infra.ScannerCliClient -     at java.base/java.net.URI.<init>(URI.java:623)
2023-07-02 08:41:26.699 [DefaultDispatcher-worker-4] INFO  c.t.a.s.infra.ScannerCliClient -     at org.archguard.scanner.ctl.client.ArchGuardHttpClient.saveDataStructure(ArchGuardHttpClient.kt:111)
2023-07-02 08:41:26.699 [DefaultDispatcher-worker-4] INFO  c.t.a.s.infra.ScannerCliClient -     at org.archguard.scanner.ctl.client.ChainedArchGuardClient.saveDataStructure(ChainedArchGuardClient.kt:15)
2023-07-02 08:41:26.699 [DefaultDispatcher-worker-4] INFO  c.t.a.s.infra.ScannerCliClient -     at org.archguard.scanner.analyser.JavaAnalyser$analyse$1.invokeSuspend(JavaAnalyser.kt:27)
2023-07-02 08:41:26.699 [DefaultDispatcher-worker-4] INFO  c.t.a.s.infra.ScannerCliClient -     at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2023-07-02 08:41:26.699 [DefaultDispatcher-worker-4] INFO  c.t.a.s.infra.ScannerCliClient -     at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
2023-07-02 08:41:26.699 [DefaultDispatcher-worker-4] INFO  c.t.a.s.infra.ScannerCliClient -     at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
2023-07-02 08:41:26.699 [DefaultDispatcher-worker-4] INFO  c.t.a.s.infra.ScannerCliClient -     at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
2023-07-02 08:41:26.699 [DefaultDispatcher-worker-4] INFO  c.t.a.s.infra.ScannerCliClient -     at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2023-07-02 08:41:26.699 [DefaultDispatcher-worker-4] INFO  c.t.a.s.infra.ScannerCliClient -     at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:279)
2023-07-02 08:41:26.699 [DefaultDispatcher-worker-4] INFO  c.t.a.s.infra.ScannerCliClient -     at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
2023-07-02 08:41:26.699 [DefaultDispatcher-worker-4] INFO  c.t.a.s.infra.ScannerCliClient -     at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
2023-07-02 08:41:26.699 [DefaultDispatcher-worker-4] INFO  c.t.a.s.infra.ScannerCliClient -     at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
2023-07-02 08:41:26.699 [DefaultDispatcher-worker-4] INFO  c.t.a.s.infra.ScannerCliClient -     at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
2023-07-02 08:41:26.699 [DefaultDispatcher-worker-4] INFO  c.t.a.s.infra.ScannerCliClient -     at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
2023-07-02 08:41:26.699 [DefaultDispatcher-worker-4] INFO  c.t.a.s.infra.ScannerCliClient -     at org.archguard.scanner.analyser.JavaAnalyser.analyse(JavaAnalyser.kt:18)
2023-07-02 08:41:26.699 [DefaultDispatcher-worker-4] INFO  c.t.a.s.infra.ScannerCliClient -     at org.archguard.scanner.core.sourcecode.LanguageSourceCodeAnalyser$DefaultImpls.analyse(LanguageSourceCodeAnalyser.kt:10)
2023-07-02 08:41:26.699 [DefaultDispatcher-worker-4] INFO  c.t.a.s.infra.ScannerCliClient -     at org.archguard.scanner.analyser.JavaAnalyser.analyse(JavaAnalyser.kt:11)
2023-07-02 08:41:26.699 [DefaultDispatcher-worker-4] INFO  c.t.a.s.infra.ScannerCliClient -     at org.archguard.scanner.ctl.loader.SourceCodeWorker$run$1.invokeSuspend(AnalyserDispatcher.kt:71)
2023-07-02 08:41:26.699 [DefaultDispatcher-worker-4] INFO  c.t.a.s.infra.ScannerCliClient -     at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2023-07-02 08:41:26.699 [DefaultDispatcher-worker-4] INFO  c.t.a.s.infra.ScannerCliClient -     at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2023-07-02 08:41:26.699 [DefaultDispatcher-worker-4] INFO  c.t.a.s.infra.ScannerCliClient -     at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:279)
<============-> 98% EXECUTING [37s]patcher-worker-4] INFO  c.t.a.s.infra.ScannerCliClient -     at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
2023-07-02 08:41:26.699 [DefaultDispatcher-worker-4] INFO  c.t.a.s.infra.ScannerCliClient -     at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
2023-07-02 08:41:26.699 [DefaultDispatcher-worker-4] INFO  c.t.a.s.infra.ScannerCliClient -     at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
2023-07-02 08:41:26.699 [DefaultDispatcher-worker-4] INFO  c.t.a.s.infra.ScannerCliClient -     at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
2023-07-02 08:41:26.699 [DefaultDispatcher-worker-4] INFO  c.t.a.s.infra.ScannerCliClient -     at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
2023-07-02 08:41:26.699 [DefaultDispatcher-worker-4] INFO  c.t.a.s.infra.ScannerCliClient -     at org.archguard.scanner.ctl.loader.SourceCodeWorker.run(AnalyserDispatcher.kt:69)
2023-07-02 08:41:26.699 [DefaultDispatcher-worker-4] INFO  c.t.a.s.infra.ScannerCliClient -     at org.archguard.scanner.ctl.loader.AnalyserDispatcher.dispatch(AnalyserDispatcher.kt:34)
2023-07-02 08:41:26.699 [DefaultDispatcher-worker-4] INFO  c.t.a.s.infra.ScannerCliClient -     at org.archguard.scanner.ctl.Runner.run(Runner.kt:92)
2023-07-02 08:41:26.699 [DefaultDispatcher-worker-4] INFO  c.t.a.s.infra.ScannerCliClient -     at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:198)
2023-07-02 08:41:26.700 [DefaultDispatcher-worker-4] INFO  c.t.a.s.infra.ScannerCliClient -     at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:18)
2023-07-02 08:41:26.700 [DefaultDispatcher-worker-4] INFO  c.t.a.s.infra.ScannerCliClient -     at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:395)
<============-> 98% EXECUTING [44s]patcher-worker-4] INFO  c.t.a.s.infra.ScannerCliClient -     at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:392)
2023-07-02 08:41:26.700 [DefaultDispatcher-worker-4] INFO  c.t.a.s.infra.ScannerCliClient -     at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.
<============-> 98% EXECUTING [45s]
2023-07-02 08:41:26.700 [DefaultDispatcher-worker-4] INFO  c.t.a.s.infra.ScannerCliClient -     at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.
kt:435)
2023-07-02 08:41:26.700 [DefaultDispatcher-worker-4] INFO  c.t.a.s.infra.ScannerCliClient -     at org.archguard.scanner.ctl.RunnerKt.main(Runner.kt:96)
2023-07-02 08:41:27.034 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - [SCANNER] o.a.s.ctl.client.ArchGuardHttpClient process topic: git-
logs
2023-07-02 08:41:27.035 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient - Exception in thread "main" java.net.URISyntaxException: Illegal ch
aracter in query at index 76: http://localhost:8081/api/scanner/2/reporting/git-logs?language=java&path=C:\Users\hanhw1\AppData\Local\Temp\archguard1682962427
0070083663
2023-07-02 08:41:27.035 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient -     at java.base/java.net.URI$Parser.fail(URI.java:2974)
2023-07-02 08:41:27.035 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient -     at java.base/java.net.URI$Parser.checkChars(URI.java:3145)
2023-07-02 08:41:27.035 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient -     at java.base/java.net.URI$Parser.parseHierarchical(URI.java:32
<============-> 98% EXECUTING [35s]
2023-07-02 08:41:27.035 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient -     at java.base/java.net.URI$Parser.parse(URI.java:3175)
2023-07-02 08:41:27.035 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient -     at java.base/java.net.URI.<init>(URI.java:623)
2023-07-02 08:41:27.035 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient -     at org.archguard.scanner.ctl.client.ArchGuardHttpClient.saveGi
<============-> 98% EXECUTING [46s]
2023-07-02 08:41:27.035 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient -     at org.archguard.scanner.ctl.client.ChainedArchGuardClient.sav
eGitLogs(ChainedArchGuardClient.kt:18)
2023-07-02 08:41:27.035 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient -     at org.archguard.scanner.analyser.GitAnalyser.analyse(GitAnaly
ser.kt:13)
<============-> 98% EXECUTING [47s]patcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient -     at org.archguard.scanner.ctl.loader.GitWorker.run(AnalyserDisp
atcher.kt:96)
2023-07-02 08:41:27.035 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient -     at org.archguard.scanner.ctl.loader.AnalyserDispatcher.dispatc
h(AnalyserDispatcher.kt:34)
2023-07-02 08:41:27.035 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient -     at org.archguard.scanner.ctl.Runner.run(Runner.kt:92)
<============-> 98% EXECUTING [48s]patcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient -     at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:198)
2023-07-02 08:41:27.035 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient -     at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:18)
2023-07-02 08:41:27.035 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient -     at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand
.kt:395)
2023-07-02 08:41:27.035 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient -     at com.github.ajalt.clikt.core.CliktCommand.parse$default(Clik
<============-> 98% EXECUTING [49s]
2023-07-02 08:41:27.035 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient -     at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.
kt:410)
2023-07-02 08:41:27.035 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient -     at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.
kt:435)
2023-07-02 08:41:27.035 [DefaultDispatcher-worker-2] INFO  c.t.a.s.infra.ScannerCliClient -     at org.archguard.scanner.ctl.RunnerKt.main(Runner.kt:96)
**Additional context**
installed server in windows .

**Comment by phodal** [comment]
I don't have Windows machine, welcome to PR to fix this.
