### ISSUE TITLE
Look me：ArchGuard 部署搭建 —— help ！！！

### ISSUE THREAD

**Issue by xuexiansen123** [archguard/archguard#14]
本人小白一枚，最近刚刚接触`ArchGuard`，在部署搭建过程中遇到一些问题，麻烦大佬们各显神通，救救小菜鸡。
以下操作按照`READ.ME`进行，如有理解不当，还请大家多多指教。
[ArchGuard scanner](https://github.com/archguard/scanner/) - scan source code, binary data and othes, and feed to database.
[ArchGuard frontend](https://github.com/archguard/archguard-frontend) - visualization results & dashboard
[ArchGuard backend](https://github.com/archguard/archguard) - connect scanner and show data.

### docker setup
`docker-compose -p ArchGuard -f ./docker-compose.yml up -d`，无报错信息，执行完毕后，需要干啥？？
```
[+] Running 7/7
 ⠿ Network archguard_dependence_network  Created                                                                               0.1s
 ⠿ Volume "archguard_mysql"              Created                                                                               0.0s
 ⠿ Volume "archguard_influxdb"           Created                                                                               0.0s
 ⠿ Container archguard_influxdb          Started                                                                               1.3s
 ⠿ Container archguard_mysql             Healthy                                                                              31.9s
 ⠿ Container archguard-backend           Started                                                                              32.1s
 ⠿ Container archguard-frontend          Started                                                                              32.3s
```

**Comment by phodal** [comment]
参照一下：[https://archguard.org/](https://archguard.org/) ，访问  http://localhost:11080/

**Comment by xuexiansen123** [comment]
> 参照一下：https://archguard.org/ ，访问 http://localhost:11080/

按照指导说明，操作如下：
1. Docker Compose 启动后，访问：http://localhost:11080/
2. 添加：https://github.com/archguard/archguard，名称 Backend，选择 Kotlin 语言，再选择扫描；然后取执行机器上执行`./docker-compose logs -f`查看后端日志打印，出现`Fail to clone source with exitCode 128`错误，按照 FAQ 中指导可能是账号密码出现错误，但是在本地执行`git clone https://账号:密码@github.com/archguard/archguard.git`完全是可以下载OK的。。。
```
archguard-backend   | 2022-04-09 10:33:37.358  INFO 1 --- [pool-1-thread-3] c.t.a.scanner.infrastructure.Processor   : fatal: unable to access 'https://账号:密码@github.com/archguard/archguard/': Failed to connect to github.com port 443: Operation timed out
archguard-backend   | 2022-04-09 10:33:37.360 ERROR 1 --- [pool-1-thread-3] c.t.a.s.d.h.HubExecutorService           : Fail to clone source with exitCode 128
archguard-backend   | 2022-04-09 10:33:37.360 ERROR 1 --- [pool-1-thread-3] t.a.s.d.a.ArchitectureDependencyAnalysis : Exception in asyncAnalyse: {}
archguard-backend   |
archguard-backend   | com.thoughtworks.archguard.scanner.domain.exception.CloneSourceException: Fail to clone source with exitCode 128
archguard-backend   |   at com.thoughtworks.archguard.scanner.domain.system.SystemOperator.cloneSingleRepo(SystemOperator.kt:52) ~[classes!/:na]
archguard-backend   |   at com.thoughtworks.archguard.scanner.domain.system.SystemOperator.cloneAndBuildAllRepo(SystemOperator.kt:35) ~[classes!/:na]
archguard-backend   |   at com.thoughtworks.archguard.scanner.domain.hubexecutor.HubExecutorService.doScan(HubExecutorService.kt:64) ~[classes!/:na]
archguard-backend   |   at com.thoughtworks.archguard.scanner.domain.hubexecutor.HubExecutorService.doScanIfNotRunning(HubExecutorService.kt:38) ~[classes!/:na]
archguard-backend   |   at com.thoughtworks.archguard.scanner.domain.analyser.ArchitectureDependencyAnalysis.analyse(ArchitectureDependencyAnalysis.kt:63) ~[classes!/:na]
archguard-backend   |   at com.thoughtworks.archguard.scanner.domain.analyser.ArchitectureDependencyAnalysis.asyncAnalyse$lambda-0(ArchitectureDependencyAnalysis.kt:48) ~[classes!/:na]
archguard-backend   |   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
archguard-backend   |   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
archguard-backend   |   at java.base/java.lang.Thread.run(Thread.java:835) ~[na:na]
archguard-backend   |
archguard-backend   | 2022-04-09 10:33:37.360  INFO 1 --- [pool-1-thread-3] t.a.s.d.a.ArchitectureDependencyAnalysis : SET SYSTEM INFO 1 SCAN FLAG TO :FAILED

```

**Comment by phodal** [comment]
@xuexiansen123 密码这个需要改成 账号 + 密码的形式，也就是填 URL，然后在下面填写用户名和密码。

**Comment by xuexiansen123** [comment]
> 

这个样子嘛？
![image](https://user-images.githubusercontent.com/61086658/162553932-81ed4960-8c61-4c10-bcc5-7d8135d42e98.png)

**Comment by phodal** [comment]
对的。

**Comment by xuexiansen123** [comment]
> 对的。

这里日志生成的链接是这个样子了，感觉更不对了啊
![image](https://user-images.githubusercontent.com/61086658/162554088-47895136-5c01-4401-9099-5e292aec21ac.png)

**Comment by xuexiansen123** [comment]
> > 对的。
> 
> 这里日志生成的链接是这个样子了，感觉更不对了啊 ![image](https://user-images.githubusercontent.com/61086658/162554088-47895136-5c01-4401-9099-5e292aec21ac.png)



> > 
> 
> 这个样子嘛？ ![image](https://user-images.githubusercontent.com/61086658/162553932-81ed4960-8c61-4c10-bcc5-7d8135d42e98.png)

**更正**：
仓库用户名 ==》 账号
仓库密码 ==》 独赢的密码
