### ISSUE TITLE
error :org.archguard.scanner.ctl.client.ArchGuardHttpClient.saveGitLogs

### ISSUE THREAD

**Issue by huiwenhan** [archguard/archguard#142]
**Describe the bug**
2024-04-10 10:45:41.092 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient - [SCANNER] o.a.s.ctl.client.ArchGuardHttpClient process topic: git-logs
2024-04-10 10:45:41.092 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient - Exception in thread "main" java.net.URISyntaxException: Illegal character in query at index 82: http://localhost:8080/api/scanner/6/reporting/git-logs?language=typescript&path=C:\Users\xxxxxx\AppData\Local\Temp\archguard16428622826288866473
2024-04-10 10:45:41.093 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient -     at java.base/java.net.URI$Parser.fail(URI.java:2995)
2024-04-10 10:45:41.093 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient -     at java.base/java.net.URI$Parser.checkChars(URI.java:3166)
2024-04-10 10:45:41.093 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient -     at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3254)
2024-04-10 10:45:41.093 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient -     at java.base/java.net.URI$Parser.parse(URI.java:3196)
2024-04-10 10:45:41.093 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient -     at java.base/java.net.URI.<init>(URI.java:645)
2024-04-10 10:45:41.093 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient -     at org.archguard.scanner.ctl.client.ArchGuardHttpClient.saveGitLogs(ArchGuardHttpClient.kt:180)
2024-04-10 10:45:41.093 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient -     at org.archguard.scanner.ctl.client.ChainedArchGuardClient.saveGitLogs(ChainedArchGuardClient.kt:18)
2024-04-10 10:45:41.093 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient -     at org.archguard.scanner.analyser.GitAnalyser.analyse(GitAnalyser.kt:13)
<============-> 98% EXECUTING [1h 25m 58s]-worker-5] INFO  c.t.a.s.infra.ScannerCliClient -     at org.archguard.scanner.ctl.loader.GitWorker.run(AnalyserDispatcher.kt:96)
2024-04-10 10:45:41.093 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient -     at org.archguard.scanner.ctl.loader.AnalyserDispatcher.dispatch(AnalyserDispatcher.kt:34)
2024-04-10 10:45:41.093 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient -     at org.archguard.scanner.ctl.Runner.run(Runner.kt:92)
2024-04-10 10:45:41.093 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient -     at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:198)
2024-04-10 10:45:41.093 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient -     at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:18)
2024-04-10 10:45:41.093 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient -     at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:395)
<============-> 98% EXECUTING [1h 25m 52s]-worker-5] INFO  c.t.a.s.infra.ScannerCliClient -     at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:392)
2024-04-10 10:45:41.093 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient -     at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:410)
2024-04-10 10:45:41.093 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient -     at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:435)
2024-04-10 10:45:41.093 [DefaultDispatcher-worker-5] INFO  c.t.a.s.infra.ScannerCliClient -     at org.archguard.scanner.ctl.RunnerKt.main(Runner.kt:96)

**Env (please complete the following information):**
 - OS: Windows 1o
 - Env:  Local dev
 - Browser chrome

**Screenshots**

![image](https://github.com/archguard/archguard/assets/302605/a0be66b2-8dad-44d6-ac19-6029e5018fc9)

**Additional context**

use enterprise private gitlab server ,  
git repository like  https://user:pass@xxxx.com  , the pass has ‘$’ character

**Comment by phodal** [comment]
setup  的时候，应该提醒了，不支持本地扫描？

**Comment by huiwenhan** [comment]
没有这样的提示，似乎是SCA分析完成，保存数据库的时候出错。

http://localhost:8080/api/scanner/6/reporting/sca-dependencies?language=typescript&path=C:\Users\xxxxx\AppData\Local\Temp\archguard16428622826288866473\src

似乎是 path中的":"导致的问题。

https://github.com/archguard/archguard/blob/master/scanner_cli/src/main/kotlin/org/archguard/scanner/ctl/client/ArchGuardHttpClient.kt


val url = "$serverUrl/api/scanner/$systemId/reporting/$topic?language=$language&path=${path.encodeUri}"

path.encodeUri 没有理解这里的用法。

**Comment by phodal** [comment]
创建的时候是有的，只在开发模式选择本地代码库，因为我没有 Windows ，所以一直没调试。欢迎来 PR

**Comment by huiwenhan** [comment]
不好意思，发现是用错环境了。 用了去年6月份的一个版本。
