### ISSUE TITLE
SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by xuexiansen123** [archguard/archguard#28]
主要操纵步骤如下：
1. `git clone https://github.com/archguard/archguard`
2. `docker-compose -p ArchGuard -f ./docker-compose.yml up -d` 所有组件启动OK
3. 参考 https://archguard.org/ ，访问 http://localhost:11080/， 创建系统
![image](https://user-images.githubusercontent.com/61086658/162563966-8cac8afc-db6a-49fa-bde8-7ce7c0e6cf1a.png)
4. `./docker-compose logs -f` 查看日志打印，出现`SSL certificate problem: unable to get local issuer certificate`错误。可以确定代码仓在机器上可以clone的
![image](https://user-images.githubusercontent.com/61086658/162564015-4b95f543-efd3-4928-b4f7-72491d073222.png)

查找网上一些解决方法【暂时未解决问题】：
（1）`git config --global http.sslVerify false`

**Comment by phodal** [comment]
你用的是 SSH 来 clone 的？

**Comment by xuexiansen123** [comment]
由于以上问题，同时存在几点疑问：
1. 看日志打印信息来看，是需要将自己需要扫描的代码下载下来，瞎子啊的

> 你用的是 SSH 来 clone 的？

不是啊，https

**Comment by phodal** [comment]
信息有点少。

**Comment by xuexiansen123** [comment]
> 信息有点少。

大佬，我现在就是仅仅 clone 代码后，执行 docker-compose 命令，然后创建系统，扫描自己代码仓库，就没有啥操作了。
根据我出现的这个问题，同时请教下：看日志打印是需要将代码下载下来，下载的问题应该就是后端机器的某个位置吧？如果是下载到本地，我这里是不是可以修改源码，将下载源码那一步删掉，我自己本地下载好就可了吧？

**Comment by phodal** [comment]
理论上，应该看为什么会出这个错误，或者你的源码的系统，本身 SSL 有问题？

**Comment by xuexiansen123** [comment]
> 
关键我本地下载都是可以的，有点不知道咋搞了。
按照我那个思路注释掉源码中clone部分，是不是可以规避下这个问题呐？
可以规避的话，麻烦如何修改下？多多感谢啦

**Comment by phodal** [comment]
你注释掉了 clone，就不知道代码在哪里了。

在新的版本里，可以先在镜像中 clone 下来，然后去数据库中，把 workdir 路径改到你 clone 的目录。

**Comment by xuexiansen123** [comment]
> 你注释掉了 clone，就不知道代码在哪里了。
> 
> 在新的版本里，可以先在镜像中 clone 下来，然后去数据库中，把 workdir 路径改到你 clone 的目录。

好的，感谢，我去研究下

**Comment by phodal** [comment]
我先 Link 一下，估计得参考一下 [SSL certificate problem: Unable to get local issuer certificate](https://confluence.atlassian.com/bitbucketserverkb/ssl-certificate-problem-unable-to-get-local-issuer-certificate-816521128.html)

我参考一下其它项目有没有这个先例：

```
git config --global http.sslVerify false
```

**Comment by xuexiansen123** [comment]
> git config --global http.sslVerify false

大佬，我的错，按照这个样子设置可以了。
应该到后端容器内执行`git config --global http.sslVerify false`，之前我一直是在docker执行机器上执行的这个命令，惭愧惭愧。
```
# 进入后端容器
docker exec -it archguard-backend /bin/sh
git config --global http.sslVerify false
```

**Comment by phodal** [comment]
帮更新一下这个 issue 的 FAQ ？ [Edit this page on GitHub.](https://github.com/archguard/archguard.org/tree/master/docs/faq.md)

**Comment by xuexiansen123** [comment]
> > git config --global http.sslVerify false
> 
> 大佬，我的错，按照这个样子设置可以了。 应该到后端容器内执行`git config --global http.sslVerify false`，之前我一直是在docker执行机器上执行的这个命令，惭愧惭愧。
> 
> ```
> # 进入后端容器
> docker exec -it archguard-backend /bin/sh
> git config --global http.sslVerify false
> ```

又遇到这个错误了`failed to scan GitSourceScanner`
```
archguard-backend   | 2022-04-12 14:34:56.506 ERROR 1 --- [pool-3-thread-3] c.t.a.s.d.hubexecutor.ScannerManager     : failed to scan GitSourceScanner
archguard-backend   |
archguard-backend   | java.net.ConnectException: Operation timed out (Connection timed out)
archguard-backend   |   at java.base/java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:na]
archguard-backend   |   at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399) ~[na:na]
archguard-backend   |   at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242) ~[na:na]
archguard-backend   |   at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224) ~[na:na]
archguard-backend   |   at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403) ~[na:na]
archguard-backend   |   at java.base/java.net.Socket.connect(Socket.java:591) ~[na:na]
archguard-backend   |   at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:285) ~[na:na]
archguard-backend   |   at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173) ~[na:na]
archguard-backend   |   at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182) ~[na:na]
archguard-backend   |   at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474) ~[na:na]
archguard-backend   |   at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569) ~[na:na]
archguard-backend   |   at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265) ~[na:na]
archguard-backend   |   at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:372) ~[na:na]
archguard-backend   |   at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:193) ~[na:na]
archguard-backend   |   at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1181) ~[na:na]
archguard-backend   |   at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1075) ~[na:na]
archguard-backend   |   at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179) ~[na:na]
archguard-backend   |   at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1581) ~[na:na]
archguard-backend   |   at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509) ~[na:na]
archguard-backend   |   at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:246) ~[na:na]
archguard-backend   |   at java.base/java.net.URL.openStream(URL.java:1140) ~[na:na]
archguard-backend   |   at com.thoughtworks.archguard.scanner.infrastructure.FileOperator.download(FileOperator.kt:14) ~[classes!/:na]
archguard-backend   |   at com.thoughtworks.archguard.scanner.domain.scanner.git.GitScannerTool.download(GitScannerTool.kt:78) ~[classes!/:na]
archguard-backend   |   at com.thoughtworks.archguard.scanner.domain.scanner.git.GitScannerTool.prepareTool(GitScannerTool.kt:55) ~[classes!/:na]
archguard-backend   |   at com.thoughtworks.archguard.scanner.domain.scanner.git.GitScannerTool.getGitReport(GitScannerTool.kt:25) ~[classes!/:na]
archguard-backend   |   at com.thoughtworks.archguard.scanner.domain.scanner.git.GitSourceScanner.scan(GitSourceScanner.kt:25) ~[classes!/:na]
archguard-backend   |   at com.thoughtworks.archguard.scanner.domain.hubexecutor.ScannerManager.execute$lambda-1$lambda-0(ScannerManager.kt:27) ~[classes!/:na]
archguard-backend   |   at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
archguard-backend   |   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
archguard-backend   |   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
archguard-backend   |   at java.base/java.lang.Thread.run(Thread.java:835) ~[na:na]
archguard-backend   |
archguard-backend   | 2022-04-12 14:34:56.506 ERROR 1 --- [pool-3-thread-1] c.t.a.s.d.hubexecutor.ScannerManager     : failed to scan SourceCodeScanner
archguard-backend   |
archguard-backend   | java.net.ConnectException: Operation timed out (Connection timed out)
archguard-backend   |   at java.base/java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:na]
archguard-backend   |   at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399) ~[na:na]
archguard-backend   |   at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242) ~[na:na]
archguard-backend   |   at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224) ~[na:na]
archguard-backend   |   at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403) ~[na:na]
archguard-backend   |   at java.base/java.net.Socket.connect(Socket.java:591) ~[na:na]
archguard-backend   |   at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:285) ~[na:na]
archguard-backend   |   at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173) ~[na:na]
archguard-backend   |   at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182) ~[na:na]
archguard-backend   |   at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474) ~[na:na]
archguard-backend   |   at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569) ~[na:na]
archguard-backend   |   at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265) ~[na:na]
archguard-backend   |   at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:372) ~[na:na]
archguard-backend   |   at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:193) ~[na:na]
archguard-backend   |   at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1181) ~[na:na]
archguard-backend   |   at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1075) ~[na:na]
archguard-backend   |   at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179) ~[na:na]
archguard-backend   |   at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1581) ~[na:na]
archguard-backend   |   at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509) ~[na:na]
archguard-backend   |   at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:246) ~[na:na]
archguard-backend   |   at java.base/java.net.URL.openStream(URL.java:1140) ~[na:na]
archguard-backend   |   at com.thoughtworks.archguard.scanner.infrastructure.FileOperator.download(FileOperator.kt:14) ~[classes!/:na]
archguard-backend   |   at com.thoughtworks.archguard.scanner.domain.scanner.codescan.sourcecode.SourceCodeTool.download(SourceCodeTool.kt:61) ~[classes!/:na]
archguard-backend   |   at com.thoughtworks.archguard.scanner.domain.scanner.codescan.sourcecode.SourceCodeTool.prepareTool(SourceCodeTool.kt:38) ~[classes!/:na]
archguard-backend   |   at com.thoughtworks.archguard.scanner.domain.scanner.codescan.sourcecode.SourceCodeTool.analyse(SourceCodeTool.kt:24) ~[classes!/:na]
archguard-backend   |   at com.thoughtworks.archguard.scanner.domain.scanner.codescan.sourcecode.SourceCodeScanner.scan(SourceCodeScanner.kt:26) ~[classes!/:na]
archguard-backend   |   at com.thoughtworks.archguard.scanner.domain.hubexecutor.ScannerManager.execute$lambda-1$lambda-0(ScannerManager.kt:27) ~[classes!/:na]
archguard-backend   |   at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
archguard-backend   |   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
archguard-backend   |   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
archguard-backend   |   at java.base/java.lang.Thread.run(Thread.java:835) ~[na:na]
archguard-backend   |
archguard-backend   | 2022-04-12 14:34:56.506  INFO 1 --- [pool-1-thread-3] t.a.s.d.a.ArchitectureDependencyAnalysis : ************************************
archguard-backend   | 2022-04-12 14:34:56.506  INFO 1 --- [pool-1-thread-3] t.a.s.d.a.ArchitectureDependencyAnalysis :  Finished level 1 scanners
archguard-backend   | 2022-04-12 14:34:56.506  INFO 1 --- [pool-1-thread-3] t.a.s.d.a.ArchitectureDependencyAnalysis : ************************************
```

**Comment by phodal** [comment]
这个还是访问 Github 下载 Scanner  的问题

**Comment by xuexiansen123** [comment]
> 这个还是访问 Github 下载 Scanner 的问题

哦哦，Scanner 没有下载下来啊，感谢

**Comment by xuexiansen123** [comment]
> 帮更新一下这个 issue 的 FAQ ？ [Edit this page on GitHub.](https://github.com/archguard/archguard.org/tree/master/docs/faq.md)

没问题，大佬，等统一搞通后，我同意整理下遇到的问题，再次感谢大佬耐心指导

**Comment by xuexiansen123** [comment]
> > 这个还是访问 Github 下载 Scanner 的问题
> 
> 哦哦，Scanner 没有下载下来啊，感谢

**Comment by xuexiansen123** [comment]
> > > > 这个还是访问 Github 下载 Scanner 的问题
> > > 
> > > 
> > > 哦哦，Scanner 没有下载下来啊，感谢
> 
> 手动直接下载最新版本的几个 jar ，然后拷贝到后端容器的`/home/spring`目录，还是报一样的错误 ![image](https://user-images.githubusercontent.com/61086658/162926511-99adef8d-2f06-4be8-bbc5-ecb527780c78.png)

修改版本号为 1.4.3 即可

**Comment by xuexiansen123** [comment]
再次感谢大佬耐心指导，完结撒花，close

**Comment by xuexiansen123** [comment]
大佬，再次请教下，我现在扫描我们公司内部python代码，粗略看大约12G，又出现这个错误了，看这个日志没有看懂啊
```
archguard-backend   | 2022-04-13 00:48:09.218 ERROR 1 --- [pool-2-thread-4] c.t.a.s.d.hubexecutor.ScannerManager     : failed to scan GitSourceScanner
archguard-backend   |
archguard-backend   | org.jdbi.v3.core.statement.UnableToExecuteStatementException: java.sql.BatchUpdateException: Data truncation: Data too long for column 'committer_email' at row 1 [statement:"null", arguments:{positional:{}, named:{}, finder:[]}]
archguard-backend   |   at org.jdbi.v3.core.statement.Batch.execute(Batch.java:86) ~[jdbi3-core-3.10.1.jar!/:3.10.1]
archguard-backend   |   at org.jdbi.v3.core.statement.Script.execute(Script.java:45) ~[jdbi3-core-3.10.1.jar!/:3.10.1]
archguard-backend   |   at com.thoughtworks.archguard.scanner.infrastructure.db.SqlScriptRunner.run(SqlScriptRunner.kt:10) ~[classes!/:na]
archguard-backend   |   at com.thoughtworks.archguard.scanner.infrastructure.db.SqlScriptRunner$$FastClassBySpringCGLIB$$180380bd.invoke(<generated>) ~[classes!/:na]
archguard-backend   |   at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.16.jar!/:5.3.16]
archguard-backend   |   at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783) ~[spring-aop-5.3.16.jar!/:5.3.16]
archguard-backend   |   at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.16.jar!/:5.3.16]
archguard-backend   |   at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753) ~[spring-aop-5.3.16.jar!/:5.3.16]
archguard-backend   |   at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137) ~[spring-tx-5.3.16.jar!/:5.3.16]
archguard-backend   |   at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.16.jar!/:5.3.16]
archguard-backend   |   at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753) ~[spring-aop-5.3.16.jar!/:5.3.16]
archguard-backend   |   at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:698) ~[spring-aop-5.3.16.jar!/:5.3.16]
archguard-backend   |   at com.thoughtworks.archguard.scanner.infrastructure.db.SqlScriptRunner$$EnhancerBySpringCGLIB$$71f3dab1.run(<generated>) ~[classes!/:na]
archguard-backend   |   at com.thoughtworks.archguard.scanner.infrastructure.db.GitSourceScanRepositoryImpl.saveGitReport(GitSourceScanRepositoryImpl.kt:36) ~[classes!/:na]
archguard-backend   |   at com.thoughtworks.archguard.scanner.infrastructure.db.GitSourceScanRepositoryImpl$$FastClassBySpringCGLIB$$e0b80fc8.invoke(<generated>) ~[classes!/:na]
archguard-backend   |   at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.16.jar!/:5.3.16]
archguard-backend   |   at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783) ~[spring-aop-5.3.16.jar!/:5.3.16]
archguard-backend   |   at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.16.jar!/:5.3.16]
archguard-backend   |   at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753) ~[spring-aop-5.3.16.jar!/:5.3.16]
archguard-backend   |   at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137) ~[spring-tx-5.3.16.jar!/:5.3.16]
archguard-backend   |   at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.16.jar!/:5.3.16]
archguard-backend   |   at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753) ~[spring-aop-5.3.16.jar!/:5.3.16]
archguard-backend   |   at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:698) ~[spring-aop-5.3.16.jar!/:5.3.16]
archguard-backend   |   at com.thoughtworks.archguard.scanner.infrastructure.db.GitSourceScanRepositoryImpl$$EnhancerBySpringCGLIB$$9591c6b2.saveGitReport(<generated>) ~[classes!/:na]
archguard-backend   |   at com.thoughtworks.archguard.scanner.domain.scanner.git.GitSourceScanner.scan(GitSourceScanner.kt:29) ~[classes!/:na]
archguard-backend   |   at com.thoughtworks.archguard.scanner.domain.hubexecutor.ScannerManager.execute$lambda-1$lambda-0(ScannerManager.kt:27) ~[classes!/:na]
archguard-backend   |   at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
archguard-backend   |   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
archguard-backend   |   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
archguard-backend   |   at java.base/java.lang.Thread.run(Thread.java:835) ~[na:na]
archguard-backend   | Caused by: java.sql.BatchUpdateException: Data truncation: Data too long for column 'committer_email' at row 1
archguard-backend   |   at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:na]
archguard-backend   |   at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:na]
archguard-backend   |   at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:na]
archguard-backend   |   at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[na:na]
archguard-backend   |   at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481) ~[na:na]
archguard-backend   |   at com.mysql.cj.util.Util.handleNewInstance(Util.java:192) ~[mysql-connector-java-8.0.28.jar!/:8.0.28]
archguard-backend   |   at com.mysql.cj.util.Util.getInstance(Util.java:167) ~[mysql-connector-java-8.0.28.jar!/:8.0.28]
archguard-backend   |   at com.mysql.cj.util.Util.getInstance(Util.java:174) ~[mysql-connector-java-8.0.28.jar!/:8.0.28]
archguard-backend   |   at com.mysql.cj.jdbc.exceptions.SQLError.createBatchUpdateException(SQLError.java:224) ~[mysql-connector-java-8.0.28.jar!/:8.0.28]
archguard-backend   |   at com.mysql.cj.jdbc.StatementImpl.executeBatchInternal(StatementImpl.java:892) ~[mysql-connector-java-8.0.28.jar!/:8.0.28]
archguard-backend   |   at com.mysql.cj.jdbc.StatementImpl.executeBatch(StatementImpl.java:795) ~[mysql-connector-java-8.0.28.jar!/:8.0.28]
archguard-backend   |   at com.alibaba.druid.filter.FilterChainImpl.statement_executeBatch(FilterChainImpl.java:3118) ~[druid-1.2.8.jar!/:1.2.8]
archguard-backend   |   at com.alibaba.druid.wall.WallFilter.statement_executeBatch(WallFilter.java:546) ~[druid-1.2.8.jar!/:1.2.8]
archguard-backend   |   at com.alibaba.druid.filter.FilterChainImpl.statement_executeBatch(FilterChainImpl.java:3116) ~[druid-1.2.8.jar!/:1.2.8]
archguard-backend   |   at com.alibaba.druid.filter.FilterAdapter.statement_executeBatch(FilterAdapter.java:2507) ~[druid-1.2.8.jar!/:1.2.8]
archguard-backend   |   at com.alibaba.druid.filter.FilterEventAdapter.statement_executeBatch(FilterEventAdapter.java:279) ~[druid-1.2.8.jar!/:1.2.8]
archguard-backend   |   at com.alibaba.druid.filter.FilterChainImpl.statement_executeBatch(FilterChainImpl.java:3116) ~[druid-1.2.8.jar!/:1.2.8]
archguard-backend   |   at com.alibaba.druid.proxy.jdbc.StatementProxyImpl.executeBatch(StatementProxyImpl.java:202) ~[druid-1.2.8.jar!/:1.2.8]
archguard-backend   |   at com.alibaba.druid.pool.DruidPooledStatement.executeBatch(DruidPooledStatement.java:803) ~[druid-1.2.8.jar!/:1.2.8]
archguard-backend   |   at org.jdbi.v3.core.statement.SqlLoggerUtil.wrap(SqlLoggerUtil.java:31) ~[jdbi3-core-3.10.1.jar!/:3.10.1]
archguard-backend   |   at org.jdbi.v3.core.statement.Batch.execute(Batch.java:84) ~[jdbi3-core-3.10.1.jar!/:3.10.1]
archguard-backend   |   ... 29 common frames omitted
archguard-backend   | Caused by: com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'committer_email' at row 1
archguard-backend   |   at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:104) ~[mysql-connector-java-8.0.28.jar!/:8.0.28]
archguard-backend   |   at com.mysql.cj.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1335) ~[mysql-connector-java-8.0.28.jar!/:8.0.28]
archguard-backend   |   at com.mysql.cj.jdbc.StatementImpl.executeBatchInternal(StatementImpl.java:858) ~[mysql-connector-java-8.0.28.jar!/:8.0.28]
archguard-backend   |   ... 40 common frames omitted
archguard-backend   |
archguard-backend   | 2022-04-13 00:48:09.219  INFO 1 --- [pool-1-thread-1] t.a.s.d.a.ArchitectureDependencyAnalysis : ************************************
archguard-backend   | 2022-04-13 00:48:09.219  INFO 1 --- [pool-1-thread-1] t.a.s.d.a.ArchitectureDependencyAnalysis :  Finished level 1 scanners
archguard-backend   | 2022-04-13 00:48:09.219  INFO 1 --- [pool-1-thread-1] t.a.s.d.a.ArchitectureDependencyAnalysis : ************************************

````

**Comment by phodal** [comment]
你开个新 issue 吧，已经和当前主题无关了。
