### ISSUE TITLE
Exception in thread "main" java.lang.StackOverflowError

### ISSUE THREAD

**Issue by nbedk** [archguard/archguard#29]
我下载的最新的代码，再按照demo分析https://gitee.com/thoughtworks/archguard.git这个项目
![image](https://user-images.githubusercontent.com/12119011/162566266-7bf0c2f3-ec1c-42d4-ab38-116f9cc24de3.png)
出现如下报错

```
Apr 09, 2022 5:29:14 PM org.archguard.ident.mysql.MysqlIdentApp analysis
INFO: select id, module_name as moduleName, fanin as fanIn, fanout as fanOut from metric_module where system_id = '' and (fanin > '' or fanout > '') , moduleName limit 10 offset 10
Apr 09, 2022 5:29:14 PM org.archguard.scanner.sourcecode.database.MysqlAnalyser analysisByNode
WARNING: error for ModuleCouplingRepositoryImpl.getCouplingAboveThreshold origin:"select id, module_name as moduleName, fanin as fanIn, fanout as fanOut from metric_module where system_id = :systemId and "+
"(fanin > :moduleFanInThreshold or fanout > :moduleFanOutThreshold) "+
orderSqlPiece+", moduleName limit :limit offset :offset"
new:select id, module_name as moduleName, fanin as fanIn, fanout as fanOut from metric_module where system_id = '' and (fanin > '' or fanout > '') , moduleName limit 10 offset 10
Exception in thread "main" java.lang.StackOverflowError
	at java.base/java.util.regex.Pattern$GroupTail.match(Pattern.java:4841)
	at java.base/java.util.regex.Pattern$Curly.match1(Pattern.java:4419)
	at java.base/java.util.regex.Pattern$Curly.match(Pattern.java:4368)
	at java.base/java.util.regex.Pattern$GroupHead.match(Pattern.java:4791)
	at java.base/java.util.regex.Pattern$Branch.match(Pattern.java:4736)
	at java.base/java.util.regex.Pattern$GroupHead.match(Pattern.java:4791)
	at java.base/java.util.regex.Pattern$Loop.match(Pattern.java:4928)
	at java.base/java.util.regex.Pattern$GroupTail.match(Pattern.java:4850)
	at java.base/java.util.regex.Pattern$BranchConn.match(Pattern.java:4700)
	at java.base/java.util.regex.Pattern$GroupTail.match(Pattern.java:4850)
	at java.base/java.util.regex.Pattern$Curly.match1(Pattern.java:4419)
	at java.base/java.util.regex.Pattern$Curly.match(Pattern.java:4368)
	at java.base/java.util.regex.Pattern$GroupHead.match(Pattern.java:4791)
```

**Comment by phodal** [comment]
应该是语义识别出了问题，后续看能不能改进一下引擎

**Comment by phodal** [comment]
在 Scanner 中修复了 Overflow 的问题
