### ISSUE TITLE
代码量约12G，出现 ERROR 1 --- [pool-2-thread-4] c.t.a.s.d.hubexecutor.ScannerManager     : failed to scan GitSourceScanner

### ISSUE THREAD

**Issue by xuexiansen123** [archguard/archguard#33]
详细日志如下，麻烦大佬帮看下，再次感谢
```
archguard-backend   | 2022-04-13 00:48:09.218 ERROR 1 --- [pool-2-thread-4] c.t.a.s.d.hubexecutor.ScannerManager     : failed to scan GitSourceScanner
archguard-backend   |
archguard-backend   | org.jdbi.v3.core.statement.UnableToExecuteStatementException: java.sql.BatchUpdateException: Data truncation: Data too long for column 'committer_email' at row 1 [statement:"null", arguments:{positional:{}, named:{}, finder:[]}]
archguard-backend   |   at org.jdbi.v3.core.statement.Batch.execute(Batch.java:86) ~[jdbi3-core-3.10.1.jar!/:3.10.1]
archguard-backend   |   at org.jdbi.v3.core.statement.Script.execute(Script.java:45) ~[jdbi3-core-3.10.1.jar!/:3.10.1]
archguard-backend   |   at com.thoughtworks.archguard.scanner.infrastructure.db.SqlScriptRunner.run(SqlScriptRunner.kt:10) ~[classes!/:na]
archguard-backend   |   at com.thoughtworks.archguard.scanner.infrastructure.db.SqlScriptRunner$$FastClassBySpringCGLIB$$180380bd.invoke(<generated>) ~[classes!/:na]
archguard-backend   |   at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.16.jar!/:5.3.16]
archguard-backend   |   at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783) ~[spring-aop-5.3.16.jar!/:5.3.16]
archguard-backend   |   at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.16.jar!/:5.3.16]
archguard-backend   |   at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753) ~[spring-aop-5.3.16.jar!/:5.3.16]
archguard-backend   |   at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137) ~[spring-tx-5.3.16.jar!/:5.3.16]
archguard-backend   |   at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.16.jar!/:5.3.16]
archguard-backend   |   at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753) ~[spring-aop-5.3.16.jar!/:5.3.16]
archguard-backend   |   at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:698) ~[spring-aop-5.3.16.jar!/:5.3.16]
archguard-backend   |   at com.thoughtworks.archguard.scanner.infrastructure.db.SqlScriptRunner$$EnhancerBySpringCGLIB$$71f3dab1.run(<generated>) ~[classes!/:na]
archguard-backend   |   at com.thoughtworks.archguard.scanner.infrastructure.db.GitSourceScanRepositoryImpl.saveGitReport(GitSourceScanRepositoryImpl.kt:36) ~[classes!/:na]
archguard-backend   |   at com.thoughtworks.archguard.scanner.infrastructure.db.GitSourceScanRepositoryImpl$$FastClassBySpringCGLIB$$e0b80fc8.invoke(<generated>) ~[classes!/:na]
archguard-backend   |   at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.16.jar!/:5.3.16]
archguard-backend   |   at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783) ~[spring-aop-5.3.16.jar!/:5.3.16]
archguard-backend   |   at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.16.jar!/:5.3.16]
archguard-backend   |   at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753) ~[spring-aop-5.3.16.jar!/:5.3.16]
archguard-backend   |   at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137) ~[spring-tx-5.3.16.jar!/:5.3.16]
archguard-backend   |   at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.16.jar!/:5.3.16]
archguard-backend   |   at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753) ~[spring-aop-5.3.16.jar!/:5.3.16]
archguard-backend   |   at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:698) ~[spring-aop-5.3.16.jar!/:5.3.16]
archguard-backend   |   at com.thoughtworks.archguard.scanner.infrastructure.db.GitSourceScanRepositoryImpl$$EnhancerBySpringCGLIB$$9591c6b2.saveGitReport(<generated>) ~[classes!/:na]
archguard-backend   |   at com.thoughtworks.archguard.scanner.domain.scanner.git.GitSourceScanner.scan(GitSourceScanner.kt:29) ~[classes!/:na]
archguard-backend   |   at com.thoughtworks.archguard.scanner.domain.hubexecutor.ScannerManager.execute$lambda-1$lambda-0(ScannerManager.kt:27) ~[classes!/:na]
archguard-backend   |   at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
archguard-backend   |   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
archguard-backend   |   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
archguard-backend   |   at java.base/java.lang.Thread.run(Thread.java:835) ~[na:na]
archguard-backend   | Caused by: java.sql.BatchUpdateException: Data truncation: Data too long for column 'committer_email' at row 1
archguard-backend   |   at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:na]
archguard-backend   |   at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:na]
archguard-backend   |   at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:na]
archguard-backend   |   at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[na:na]
archguard-backend   |   at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481) ~[na:na]
archguard-backend   |   at com.mysql.cj.util.Util.handleNewInstance(Util.java:192) ~[mysql-connector-java-8.0.28.jar!/:8.0.28]
archguard-backend   |   at com.mysql.cj.util.Util.getInstance(Util.java:167) ~[mysql-connector-java-8.0.28.jar!/:8.0.28]
archguard-backend   |   at com.mysql.cj.util.Util.getInstance(Util.java:174) ~[mysql-connector-java-8.0.28.jar!/:8.0.28]
archguard-backend   |   at com.mysql.cj.jdbc.exceptions.SQLError.createBatchUpdateException(SQLError.java:224) ~[mysql-connector-java-8.0.28.jar!/:8.0.28]
archguard-backend   |   at com.mysql.cj.jdbc.StatementImpl.executeBatchInternal(StatementImpl.java:892) ~[mysql-connector-java-8.0.28.jar!/:8.0.28]
archguard-backend   |   at com.mysql.cj.jdbc.StatementImpl.executeBatch(StatementImpl.java:795) ~[mysql-connector-java-8.0.28.jar!/:8.0.28]
archguard-backend   |   at com.alibaba.druid.filter.FilterChainImpl.statement_executeBatch(FilterChainImpl.java:3118) ~[druid-1.2.8.jar!/:1.2.8]
archguard-backend   |   at com.alibaba.druid.wall.WallFilter.statement_executeBatch(WallFilter.java:546) ~[druid-1.2.8.jar!/:1.2.8]
archguard-backend   |   at com.alibaba.druid.filter.FilterChainImpl.statement_executeBatch(FilterChainImpl.java:3116) ~[druid-1.2.8.jar!/:1.2.8]
archguard-backend   |   at com.alibaba.druid.filter.FilterAdapter.statement_executeBatch(FilterAdapter.java:2507) ~[druid-1.2.8.jar!/:1.2.8]
archguard-backend   |   at com.alibaba.druid.filter.FilterEventAdapter.statement_executeBatch(FilterEventAdapter.java:279) ~[druid-1.2.8.jar!/:1.2.8]
archguard-backend   |   at com.alibaba.druid.filter.FilterChainImpl.statement_executeBatch(FilterChainImpl.java:3116) ~[druid-1.2.8.jar!/:1.2.8]
archguard-backend   |   at com.alibaba.druid.proxy.jdbc.StatementProxyImpl.executeBatch(StatementProxyImpl.java:202) ~[druid-1.2.8.jar!/:1.2.8]
archguard-backend   |   at com.alibaba.druid.pool.DruidPooledStatement.executeBatch(DruidPooledStatement.java:803) ~[druid-1.2.8.jar!/:1.2.8]
archguard-backend   |   at org.jdbi.v3.core.statement.SqlLoggerUtil.wrap(SqlLoggerUtil.java:31) ~[jdbi3-core-3.10.1.jar!/:3.10.1]
archguard-backend   |   at org.jdbi.v3.core.statement.Batch.execute(Batch.java:84) ~[jdbi3-core-3.10.1.jar!/:3.10.1]
archguard-backend   |   ... 29 common frames omitted
archguard-backend   | Caused by: com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'committer_email' at row 1
archguard-backend   |   at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:104) ~[mysql-connector-java-8.0.28.jar!/:8.0.28]
archguard-backend   |   at com.mysql.cj.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1335) ~[mysql-connector-java-8.0.28.jar!/:8.0.28]
archguard-backend   |   at com.mysql.cj.jdbc.StatementImpl.executeBatchInternal(StatementImpl.java:858) ~[mysql-connector-java-8.0.28.jar!/:8.0.28]
archguard-backend   |   ... 40 common frames omitted
archguard-backend   |
archguard-backend   | 2022-04-13 00:48:09.219  INFO 1 --- [pool-1-thread-1] t.a.s.d.a.ArchitectureDependencyAnalysis : ************************************
archguard-backend   | 2022-04-13 00:48:09.219  INFO 1 --- [pool-1-thread-1] t.a.s.d.a.ArchitectureDependencyAnalysis :  Finished level 1 scanners
archguard-backend   | 2022-04-13 00:48:09.219  INFO 1 --- [pool-1-thread-1] t.a.s.d.a.ArchitectureDependencyAnalysis : ************************************
```

**Comment by phodal** [comment]
表面上的错误是 `committer_email` 的邮箱太长了，也有可能是 SQL 顺序导致的，问题应该出在 Scanner 里。

**Comment by xuexiansen123** [comment]
> 表面上的错误是 `committer_email` 的邮箱太长了，也有可能是 SQL 顺序导致的，问题应该出在 Scanner 里。

测试了几个代码量少的库，暂时没有出现这个问题，难道代码量太大，就会引入问题了？

**Comment by phodal** [comment]
理论上应该在 #2bbecac14106ad601aea9f010391c601a7d84d13 中修了，下次新版本的时候再验证

**Comment by xuexiansen123** [comment]
> 理论上应该在 #2bbecac14106ad601aea9f010391c601a7d84d13 中修了，下次新版本的时候再验证

好的，后面再测试下，再次感谢
