### ISSUE TITLE
无法链接私有仓库

### ISSUE THREAD

**Issue by xiaoshyang** [archguard/archguard#39]
**Describe the bug**
使用的公司的私有仓库，配置了地址和登录的用户名和密码，扫描没有异常，查看日志发现ssl连接有问题
**Env (please complete the following information):**
 - OS: macos，Docker Desktop 4.7.0 (77141)
 - Env: Docker compose
 - Browser [e.g.  edge ]
 - Version [e.g. 98.0.1108.55 (官方内部版本) (x86_64)]

异常信息：

```
022-04-15 15:38:11.981  INFO 1 --- [pool-1-thread-2] c.t.a.s.domain.system.SystemOperator     : workSpace is: /tmp/archguard17943594146772129611
2022-04-15 15:38:11.981  INFO 1 --- [pool-1-thread-2] c.t.a.s.domain.system.SystemOperator     : workSpace is /tmp/archguard17943594146772129611 repo is: https://coding.xxxxx.com/xxxx/xxx-xxxxx.git
2022-04-15 15:38:12.129  INFO 1 --- [pool-1-thread-2] c.t.a.s.i.command.Processor              : HEAD is now at 6e817eaba 鏃ュ織鎷艰绉诲嚭
2022-04-15 15:38:12.154  INFO 1 --- [pool-1-thread-2] c.t.a.s.i.command.Processor              : Removing scm_git_hot_file.txt
2022-04-15 15:38:12.557  INFO 1 --- [pool-1-thread-2] c.t.a.s.i.command.Processor              : From https://coding.xxxxx.com/xxxx/xxx-xxxxx.git
2022-04-15 15:38:12.557  INFO 1 --- [pool-1-thread-2] c.t.a.s.i.command.Processor              :  * branch                master     -> FETCH_HEAD
2022-04-15 15:38:12.564  INFO 1 --- [pool-1-thread-2] c.t.a.s.i.command.Processor              : Already up to date.
2022-04-15 15:38:12.577  INFO 1 --- [pool-1-thread-2] c.t.a.s.i.command.Processor              : Current branch master is up to date.
2022-04-15 15:38:12.582  INFO 1 --- [pool-8-thread-1] c.t.a.s.d.s.c.sourcecode.SourceCodeTool  : start download scan_sourcecode Tool
2022-04-15 15:38:12.584  INFO 1 --- [pool-8-thread-2] c.t.a.s.d.s.j.tbs.TestBadSmellScanner    : start scan test bad smell
2022-04-15 15:38:12.584  INFO 1 --- [pool-8-thread-2] c.t.a.s.d.s.j.tbs.TestBadsmellTool       : start download scan_test_badsmell tool
2022-04-15 15:38:12.585  INFO 1 --- [pool-8-thread-4] c.t.a.s.d.scanner.git.GitSourceScanner   : start scan git source
2022-04-15 15:38:12.586  INFO 1 --- [pool-8-thread-4] c.t.a.s.d.scanner.git.GitScannerTool     : start download scan_git tool
2022-04-15 15:38:12.801 ERROR 1 --- [pool-8-thread-2] c.t.a.s.d.hubexecutor.ScannerManager     : failed to scan TestBadSmellScanner

javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
        at java.base/sun.security.ssl.SSLSocketImpl.handleEOF(SSLSocketImpl.java:1349) ~[na:na]
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1188) ~[na:na]
        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1091) ~[na:na]
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:402) ~[na:na]
        at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567) ~[na:na]
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:187) ~[na:na]
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1581) ~[na:na]
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509) ~[na:na]
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:246) ~[na:na]
        at java.base/java.net.URL.openStream(URL.java:1140) ~[na:na]
        at com.thoughtworks.archguard.scanner.infrastructure.FileOperator.download(FileOperator.kt:14) ~[classes!/:na]
        at com.thoughtworks.archguard.scanner.domain.scanner.javaext.tbs.TestBadsmellTool.download(TestBadsmellTool.kt:63) ~[classes!/:na]
        at com.thoughtworks.archguard.scanner.domain.scanner.javaext.tbs.TestBadsmellTool.prepareTool(TestBadsmellTool.kt:22) ~[classes!/:na]
        at com.thoughtworks.archguard.scanner.domain.scanner.javaext.tbs.TestBadsmellTool.getTestBadSmellReport(TestBadsmellTool.kt:27) ~[classes!/:na]
        at com.thoughtworks.archguard.scanner.domain.scanner.javaext.tbs.TestBadSmellScanner.scan(TestBadSmellScanner.kt:31) ~[classes!/:na]
        at com.thoughtworks.archguard.scanner.domain.hubexecutor.ScannerManager.execute$lambda-1$lambda-0(ScannerManager.kt:27) ~[classes!/:na]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:835) ~[na:na]
Caused by: java.io.EOFException: SSL peer shut down incorrectly
        at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:167) ~[na:na]
        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:108) ~[na:na]
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1180) ~[na:na]
        ... 18 common frames omitted

2022-04-15 15:38:12.801 ERROR 1 --- [pool-8-thread-1] c.t.a.s.d.hubexecutor.ScannerManager     : failed to scan SourceCodeScanner

javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
        at java.base/sun.security.ssl.SSLSocketImpl.handleEOF(SSLSocketImpl.java:1349) ~[na:na]
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1188) ~[na:na]
        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1091) ~[na:na]
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:402) ~[na:na]
        at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567) ~[na:na]
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:187) ~[na:na]
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1581) ~[na:na]
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509) ~[na:na]
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:246) ~[na:na]
        at java.base/java.net.URL.openStream(URL.java:1140) ~[na:na]
        at com.thoughtworks.archguard.scanner.infrastructure.FileOperator.download(FileOperator.kt:14) ~[classes!/:na]
        at com.thoughtworks.archguard.scanner.domain.scanner.codescan.sourcecode.SourceCodeTool.download(SourceCodeTool.kt:61) ~[classes!/:na]
        at com.thoughtworks.archguard.scanner.domain.scanner.codescan.sourcecode.SourceCodeTool.prepareTool(SourceCodeTool.kt:38) ~[classes!/:na]
        at com.thoughtworks.archguard.scanner.domain.scanner.codescan.sourcecode.SourceCodeTool.analyse(SourceCodeTool.kt:24) ~[classes!/:na]
        at com.thoughtworks.archguard.scanner.domain.scanner.codescan.sourcecode.SourceCodeScanner.scan(SourceCodeScanner.kt:26) ~[classes!/:na]
        at com.thoughtworks.archguard.scanner.domain.hubexecutor.ScannerManager.execute$lambda-1$lambda-0(ScannerManager.kt:27) ~[classes!/:na]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:835) ~[na:na]
Caused by: java.io.EOFException: SSL peer shut down incorrectly
        at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:167) ~[na:na]
        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:108) ~[na:na]
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1180) ~[na:na]
        ... 18 common frames omitted

2022-04-15 15:38:12.801 ERROR 1 --- [pool-8-thread-4] c.t.a.s.d.hubexecutor.ScannerManager     : failed to scan GitSourceScanner

javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
        at java.base/sun.security.ssl.SSLSocketImpl.handleEOF(SSLSocketImpl.java:1349) ~[na:na]
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1188) ~[na:na]
        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1091) ~[na:na]
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:402) ~[na:na]
        at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567) ~[na:na]
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:187) ~[na:na]
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1581) ~[na:na]
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509) ~[na:na]
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:246) ~[na:na]
        at java.base/java.net.URL.openStream(URL.java:1140) ~[na:na]
        at com.thoughtworks.archguard.scanner.infrastructure.FileOperator.download(FileOperator.kt:14) ~[classes!/:na]
        at com.thoughtworks.archguard.scanner.domain.scanner.git.GitScannerTool.download(GitScannerTool.kt:78) ~[classes!/:na]
        at com.thoughtworks.archguard.scanner.domain.scanner.git.GitScannerTool.prepareTool(GitScannerTool.kt:55) ~[classes!/:na]
        at com.thoughtworks.archguard.scanner.domain.scanner.git.GitScannerTool.getGitReport(GitScannerTool.kt:25) ~[classes!/:na]
        at com.thoughtworks.archguard.scanner.domain.scanner.git.GitSourceScanner.scan(GitSourceScanner.kt:25) ~[classes!/:na]
        at com.thoughtworks.archguard.scanner.domain.hubexecutor.ScannerManager.execute$lambda-1$lambda-0(ScannerManager.kt:27) ~[classes!/:na]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:835) ~[na:na]
Caused by: java.io.EOFException: SSL peer shut down incorrectly
        at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:167) ~[na:na]
        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:108) ~[na:na]
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1180) ~[na:na]
        ... 18 common frames omitted

2022-04-15 15:38:14.735  INFO 1 --- [pool-8-thread-3] c.t.a.s.d.scanner.git.GitHotFileScanner  : Saved gitHotFiles, systemId=1
```

**Comment by phodal** [comment]
看了一下日志，代码 Clone 没有问题，就是 Scanner 没有下载下来。

**Comment by xiaoshyang** [comment]
重新下载后，没问题了，谢谢
