### ISSUE TITLE
docker-compose 安装之后扫描项目报错

### ISSUE THREAD

**Issue by jxljf** [archguard/archguard#6]
```
archguard-backend     | 2022-04-07 11:29:25.008 ERROR 1 --- [pool-1-thread-3] t.a.s.d.a.ArchitectureDependencyAnalysis : Exception in asyncAnalyse: {}
archguard-backend     |
archguard-backend     | com.thoughtworks.archguard.scanner.domain.exception.CloneSourceException: Fail to clone source with exitCode 128
archguard-backend     |         at com.thoughtworks.archguard.scanner.domain.system.SystemOperator.cloneSingleRepo(SystemOperator.kt:52) ~[classes!/:na]
archguard-backend     |         at com.thoughtworks.archguard.scanner.domain.system.SystemOperator.cloneAndBuildAllRepo(SystemOperator.kt:35) ~[classes!/:na]
archguard-backend     |         at com.thoughtworks.archguard.scanner.domain.hubexecutor.HubExecutorService.doScan(HubExecutorService.kt:64) ~[classes!/:na]
archguard-backend     |         at com.thoughtworks.archguard.scanner.domain.hubexecutor.HubExecutorService.doScanIfNotRunning(HubExecutorService.kt:38) ~[classes!/:na]
archguard-backend     |         at com.thoughtworks.archguard.scanner.domain.analyser.ArchitectureDependencyAnalysis.analyse(ArchitectureDependencyAnalysis.kt:63) ~[classes!/:na]
archguard-backend     |         at com.thoughtworks.archguard.scanner.domain.analyser.ArchitectureDependencyAnalysis.asyncAnalyse$lambda-0(ArchitectureDependencyAnalysis.kt:48) ~[classes!/:na]
archguard-backend     |         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
archguard-backend     |         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
```

**Comment by phodal** [comment]
你用的是内网？还是 Github 这种？需要用户名和密码吗？

**Comment by jxljf** [comment]
> 你用的是内网？还是 Github 这种？需要用户名和密码吗？

对，是内网，需要用户名和密码

**Comment by phodal** [comment]
需要 `docker exec -it archguard-backend sh` 进去看看

**Comment by jxljf** [comment]
好了，是我自己的账号写错了
