### ISSUE TITLE
服务更新之后启动失败

### ISSUE THREAD

**Issue by 1175239102** [archguard/archguard#82]
我首先关闭了docker服务(docker-compose down)，今天从github上拉下来最近代码，删除了镜像，执行命令docker-compose -p ArchGuard -f ./docker-compose.yml up -d重新去拉去新的镜像，然后失败了archguard/archguard-backend:latest
Detected failed migration to version 202206020001 (add governance issue). Please remove any half-completed changes then run repair to fix the schema history.
Need more flexibility with validation rules? Learn more: https://rd.gt/3AbJUZE
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:229)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)

**Comment by phodal** [comment]
@1175239102 可以 pull 一下再试试

**Comment by 1175239102** [comment]
重新更新启动没问题，以后更新是否都需要手动删除库中的版本号

**Comment by phodal** [comment]
不需要，应该只是 alpha.17 里引入了 bug，只要没安装过 alpha 17 就不会出现了
