### ISSUE TITLE
系统分析指标不完整

### ISSUE THREAD

**Issue by duguyixiaono1** [archguard/archguard#85]
系统分析后，控制台报下面的异常：
`2022-06-09 15:13:54.447 [pool-1-thread-5] INFO  c.t.a.s.d.a.ArchitectureDependencyAnalysis - ************************************
2022-06-09 15:13:54.447 [pool-1-thread-5] INFO  c.t.a.s.d.a.ArchitectureDependencyAnalysis -  Finished level 2 analysis metrics
2022-06-09 15:13:54.447 [pool-1-thread-5] INFO  c.t.a.s.d.a.ArchitectureDependencyAnalysis - ************************************
2022-06-09 15:13:55.029 [http-nio-8080-exec-2] ERROR c.t.a.m.i.influx.InfluxDBClient - Client exception when send metrics to InfluxDB. {}
org.springframework.web.client.HttpClientErrorException$Unauthorized: 401 Unauthorized: [no body]
	at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:105)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:168)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:122)
	at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:819)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:777)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:711)
	at org.springframework.web.client.RestTemplate.postForObject(RestTemplate.java:437)
	at com.thoughtworks.archguard.metrics.infrastructure.influx.InfluxDBClient.save(InfluxDBClient.kt:19)
	at com.thoughtworks.archguard.metrics.infrastructure.MetricsRepositoryImpl.insertAllClassCouplings(MetricsRepositoryImpl.kt:24)
	at com.thoughtworks.archguard.metrics.infrastructure.MetricsRepositoryImpl$$FastClassBySpringCGLIB$$b2127064.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
	at com.thoughtworks.archguard.metrics.infrastructure.MetricsRepositoryImpl$$EnhancerBySpringCGLIB$$d41d6c69.insertAllClassCouplings(<generated>)
	at com.thoughtworks.archguard.metrics.domain.coupling.CouplingServiceImpl.persistAllClassCouplingResults(CouplingServiceImpl.kt:24)
	at com.thoughtworks.archguard.code.module.domain.LogicModuleService.autoDefineLogicModule(LogicModuleService.kt:62)
	at com.thoughtworks.archguard.code.module.controller.LogicModuleController.autoDefineLogicModule(LogicModuleController.kt:90)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:681)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1743)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:833)
2022-06-09 15:13:55.029 [pool-1-thread-5] INFO  c.t.a.s.i.c.AnalysisModuleClient - Auto-define request to module-analysis for system 1
2022-06-09 15:13:55.029 [pool-1-thread-5] INFO  c.t.a.s.d.a.ArchitectureDependencyAnalysis - ************************************
2022-06-09 15:13:55.029 [pool-1-thread-5] INFO  c.t.a.s.d.a.ArchitectureDependencyAnalysis -  Finished logic module auto define
2022-06-09 15:13:55.029 [pool-1-thread-5] INFO  c.t.a.s.d.a.ArchitectureDependencyAnalysis - ************************************`

influxdb server端报如下异常：
2022-06-09T07:01:28.973888Z	info	Unauthorized	{"log_id": "0ayewLQ0000", "error": "token required"}
2022-06-09T07:01:29.052127Z	info	Unauthorized	{"log_id": "0ayewLQ0000", "error": "token required"}
2022-06-09T07:13:55.025657Z	info	Unauthorized	{"log_id": "0ayewLQ0000", "error": "token required"}
2022-06-09T07:13:55.104592Z	info	Unauthorized	{"log_id": "0ayewLQ0000", "error": "token required"}
2022-06-09T07:13:55.141257Z	info	Unauthorized	{"log_id": "0ayewLQ0000", "error": "token required"}
2022-06-09T07:13:55.212737Z	info	Unauthorized	{"log_id": "0ayewLQ0000", "error": "token required"}
2022-06-09T07:13:55.219839Z	info	Unauthorized	{"log_id": "0ayewLQ0000", "error": "token required"}
2022-06-09T07:13:55.303146Z	info	Unauthorized	{"log_id": "0ayewLQ0000", "error": "token required"}

我感觉我本地mac influxdb没有配置正确，但没找到，求助

**Comment by phodal** [comment]
InfluxDB 使用的是 1.x ？

**Comment by duguyixiaono1** [comment]
> InfluxDB 使用的是 1.x ？

deMacBook-Pro ~ % influx version
Influx CLI 2.3.0 (git: 88ba3464cd) build_date: 2022-03-18T22:21:12Z

**Comment by phodal** [comment]
现在只支持 1.x，不兼容 2.x

**Comment by duguyixiaono1** [comment]
> 现在只支持 1.x，不兼容 2.x

好吧，setup里没看到相关介绍，还在debug influx http api :(

**Comment by phodal** [comment]
可以来个 PR，加一下
